FROM node:24-alpine AS build

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable && corepack prepare pnpm@10.18.3 --activate

WORKDIR /workhorse
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm build:core && pnpm docs:build

FROM nginx:1.29-alpine AS runtime

COPY deployment/site.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workhorse/site/dist/client/ /usr/share/nginx/html/

EXPOSE 8080
