/**
 * Writes the one stylesheet that carries every token colour on this site.
 *
 * The two highlighting pipelines run in separate processes and emit class names
 * rather than styles, so neither can write the rules those classes need. This
 * script highlights the same code both of them will, with the same theme pairs,
 * and collects the rules. A class name stands for the colours it was derived
 * from, so a rule written here matches the class written there.
 *
 * It runs before both pipelines. If it ever misses a code block, that block's
 * tokens render in the inherited foreground colour rather than wrongly, and
 * `site-smoke` catches the larger failure of the transformers coming apart.
 *
 * A token with no colour of its own, such as one in a fence that declares no
 * language, yields a class with an empty rule. That is correct: the token takes
 * the colour the `pre` carries. The bundler drops the empty rule, so the class
 * appears in the markup with nothing to match, and nothing depends on it.
 */
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";

import { highlight } from "fumadocs-core/highlight";

import {
  createTokenClassTransformer,
  docsCodeThemes,
  landingCodeThemes,
} from "../lib/code-highlighting.js";
import {
  landingSnippetLanguages,
  landingSnippets,
  type LandingSnippetId,
} from "../lib/landing-snippets.js";

const contentRoot = new URL("../content/", import.meta.url);

/** Every fenced block in one MDX file, with the language it declares. */
function fencedBlocks(source: string): { lang: string; code: string }[] {
  const blocks: { lang: string; code: string }[] = [];
  // A fence opens with three or more backticks and closes on the same count, so
  // a block that itself contains a fence does not end early.
  const fence = /^([ \t]*)(`{3,})([^\n`]*)\n([\s\S]*?)^[ \t]*\2[ \t]*$/gm;
  for (const match of source.matchAll(fence)) {
    const meta = (match[3] ?? "").trim();
    // A fence with no language still reaches Shiki, which colours it in the
    // theme's plain foreground. That is one more token style, and a page using
    // it would otherwise carry a class with no rule.
    const lang = meta.split(/\s+/)[0] || "text";
    blocks.push({ lang, code: match[4] ?? "" });
  }
  return blocks;
}

async function mdxFiles(directory: URL): Promise<URL[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const found: URL[] = [];
  for (const entry of entries) {
    if (entry.isDirectory()) {
      found.push(...(await mdxFiles(new URL(`${entry.name}/`, directory))));
    } else if (entry.name.endsWith(".mdx")) {
      found.push(new URL(entry.name, directory));
    }
  }
  return found;
}

const transformer = createTokenClassTransformer();

// Fumadocs resolves an unknown language by falling back, and a language Shiki
// cannot load throws. Neither should fail the build over one code fence, but the
// miss has to be visible rather than silent.
async function collect(code: string, lang: string, themes: Record<string, string>) {
  try {
    await highlight(code, { lang, themes, defaultColor: false, transformers: [transformer] });
  } catch (error) {
    process.stderr.write(`  skipped a ${lang} block: ${(error as Error).message}\n`);
  }
}

let documentationBlocks = 0;
for (const file of await mdxFiles(contentRoot)) {
  for (const block of fencedBlocks(await readFile(file, "utf8"))) {
    documentationBlocks += 1;
    await collect(block.code, block.lang, docsCodeThemes);
  }
}

for (const [id, code] of Object.entries(landingSnippets)) {
  await collect(code, landingSnippetLanguages[id as LandingSnippetId] ?? "ts", landingCodeThemes);
}

const css = transformer.getCSS();

// Two different styles that shortened to one class would colour tokens wrongly
// and silently. The registry is keyed by the full name, so a shortened name
// appearing twice in the rules is the collision.
const ruleNames = [...css.matchAll(/\.([A-Za-z0-9_-]+)\{/g)].map((match) => match[1]);
const duplicates = ruleNames.filter((name, index) => ruleNames.indexOf(name) !== index);
if (duplicates.length > 0) {
  throw new Error(
    `Two token styles shortened to the same class: ${[...new Set(duplicates)].join(", ")}. Lengthen shortenTokenClass.`,
  );
}

const outDirectory = new URL("../.source/", import.meta.url);
await mkdir(outDirectory, { recursive: true });
await writeFile(
  new URL("code-theme.css", outDirectory),
  `/* Generated by scripts/gen-code-theme.ts. Every token colour on the site. */\n${css}\n`,
);

process.stdout.write(
  `Wrote ${ruleNames.length} token classes from ${documentationBlocks} documentation blocks and ${Object.keys(landingSnippets).length} landing snippets (${css.length} bytes)\n`,
);
