"""Render the public Python API of ``workhorse`` as a stable text snapshot.

ADR 0054 defines the Python API as the names in a public module's ``__all__``. This tool reproduces
that definition: it walks the installed package for modules whose every path segment avoids a
leading underscore, reads each one's ``__all__``, and prints the shape a caller reaches through each
name. ``scripts/generate-python-api.ts`` writes the result to ``api/python.txt``, so a removed name
or a narrowed signature shows up as a deleted or changed line.

Introspection rather than parsing, because ``__all__`` re-exports across modules and only the
imported object knows where it was defined. Inherited members are printed with declared ones: a
caller reaches them the same way, so dropping a base class is as breaking as deleting the member.
"""

from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import pkgutil
import re
import sys
import types
import typing
from collections.abc import Callable, Sequence
from pathlib import Path

HEADER = """# Public Python API
#
# Generated by `pnpm python-api:generate` from the installed `workhorse` package. ADR 0054 governs
# this surface: a removed or renamed name in a public module's `__all__` and a narrowed signature
# are breaking, and an addition is not. An underscore-prefixed module is private and absent here.
"""

# Dunder members a caller calls directly, so they belong to the surface.
PROTOCOL_MEMBERS = frozenset(
    {
        "__aenter__",
        "__aexit__",
        "__aiter__",
        "__anext__",
        "__call__",
        "__enter__",
        "__exit__",
        "__init__",
        "__iter__",
        "__next__",
    }
)

# Attributes Python puts on every class, every exception, or every dataclass.
IMPLICIT_MEMBERS = frozenset(
    {
        "add_note",
        "args",
        "count",
        "index",
        "mro",
        "with_traceback",
    }
)


def module_names(package: str) -> list[str]:
    """Public modules of a package, the package itself first, then depth-first by name."""
    root = importlib.import_module(package)
    found = [package]
    for info in pkgutil.walk_packages(root.__path__, prefix=f"{package}."):
        if any(segment.startswith("_") for segment in info.name.split(".")[1:]):
            continue
        found.append(info.name)
    return sorted(found)


class Renderer:
    """Renders one distribution's public modules, caching each module's parsed source."""

    def __init__(self) -> None:
        self._sources: dict[str, tuple[ast.Module | None, str]] = {}

    def _source(self, module_name: str) -> tuple[ast.Module | None, str]:
        if module_name not in self._sources:
            module = sys.modules.get(module_name)
            if module is None:
                self._sources[module_name] = (None, "")
            else:
                try:
                    text = inspect.getsource(module)
                except (OSError, TypeError):
                    self._sources[module_name] = (None, "")
                else:
                    self._sources[module_name] = (ast.parse(text), text)
        return self._sources[module_name]

    def type_alias_source(self, alias: typing.TypeAliasType) -> str | None:
        """The right-hand side of a ``type X = ...`` statement, exactly as written."""
        origin = getattr(alias, "__module__", None)
        if origin is None:
            return None
        tree, text = self._source(origin)
        if tree is None:
            return None
        for node in tree.body:
            if isinstance(node, ast.TypeAlias) and node.name.id == alias.__name__:
                return ast.get_source_segment(text, node.value)
        return None

    def annotation(self, value: object) -> str:
        """A source-shaped rendering of one annotation.

        Modules that import ``annotations`` from ``__future__`` store the text a reader wrote, and
        the rest store the object it evaluates to. Normalising the second form to the first keeps
        one module's move to postponed evaluation out of the snapshot.
        """
        if isinstance(value, str):
            return value
        if value is None:
            return "None"
        if isinstance(value, type) and value.__module__ == "builtins":
            return value.__qualname__
        rendered = repr(value) if not isinstance(value, type) else f"{value.__qualname__}"
        return re.sub(
            r"\b(?:typing|collections\.abc|workhorse[\w.]*|datetime|decimal)\.", "", rendered
        )

    def signature(self, name: str, function: Callable[..., object]) -> str:
        """One ``def`` line, with every annotation rendered the way the source writes it."""
        try:
            signature = inspect.signature(function)
        except (TypeError, ValueError):
            return f"def {name}(...)"
        rendered: list[str] = []
        for parameter in signature.parameters.values():
            text = parameter.name
            if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
                text = f"*{text}"
            elif parameter.kind is inspect.Parameter.VAR_KEYWORD:
                text = f"**{text}"
            elif parameter.kind is inspect.Parameter.KEYWORD_ONLY and "*" not in rendered:
                rendered.append("*")
            if parameter.annotation is not inspect.Parameter.empty:
                text = f"{text}: {self.annotation(parameter.annotation)}"
            if parameter.default is not inspect.Parameter.empty:
                separator = " = " if parameter.annotation is not inspect.Parameter.empty else "="
                text = f"{text}{separator}{self.value(parameter.default)}"
            rendered.append(text)
        returns = (
            ""
            if signature.return_annotation is inspect.Signature.empty
            else f" -> {self.annotation(signature.return_annotation)}"
        )
        prefix = "async def" if inspect.iscoroutinefunction(function) else "def"
        return f"{prefix} {name}({', '.join(rendered)}){returns}"

    def value(self, value: object) -> str:
        """A default or constant, printed when its identity is stable and named otherwise."""
        if isinstance(value, str | int | float | bool | bytes | None):
            return repr(value)
        if isinstance(value, tuple | frozenset) and not value:
            return repr(value)
        if isinstance(value, type):
            return value.__qualname__
        if callable(value) and hasattr(value, "__name__"):
            return f"<{value.__name__}>"
        return f"<{type(value).__qualname__}>"

    def members(self, cls: type) -> list[str]:
        """Every member a caller reaches on a class, own and inherited, sorted by name."""
        annotations: dict[str, object] = {}
        for base in reversed(cls.__mro__):
            if base is object:
                continue
            annotations.update(inspect.get_annotations(base))
        names = {name for name in dir(cls) if not name.startswith("_")}
        names |= {name for name in dir(cls) if name in PROTOCOL_MEMBERS}
        names |= {name for name in annotations if not name.startswith("_")}
        names -= IMPLICIT_MEMBERS
        lines: list[str] = []
        for name in sorted(names):
            attribute = inspect.getattr_static(cls, name, None)
            if isinstance(attribute, property):
                getter = attribute.fget
                returns = "" if getter is None else self.signature(name, getter).split(") ", 1)[-1]
                lines.append(f"  @property {name}{'' if not returns else f' {returns}'}")
            elif isinstance(attribute, staticmethod | classmethod):
                kind = "staticmethod" if isinstance(attribute, staticmethod) else "classmethod"
                lines.append(f"  @{kind} {self.signature(name, attribute.__func__)}")
            elif inspect.isroutine(attribute):
                lines.append(f"  {self.signature(name, attribute)}")
            elif name in annotations:
                declared = f"  {name}: {self.annotation(annotations[name])}"
                if name in vars(cls):
                    declared = f"{declared} = {self.value(vars(cls)[name])}"
                lines.append(declared)
            else:
                lines.append(f"  {name} = {self.value(attribute)}")
        return lines

    def render(self, name: str, obj: object) -> list[str]:
        """One ``__all__`` name and, for a class, its members."""
        if isinstance(obj, typing.TypeAliasType):
            source = self.type_alias_source(obj)
            return [f"type {name} = {source if source else self.annotation(obj.__value__)}"]
        if typing.get_origin(obj) is not None or isinstance(obj, types.UnionType):
            return [f"type {name} = {self.annotation(obj)}"]
        if isinstance(obj, typing.TypeVar):
            bound = "" if obj.__bound__ is None else f" bound={self.annotation(obj.__bound__)}"
            return [f"typevar {name}{bound}"]
        if isinstance(obj, type):
            bases = [base.__qualname__ for base in obj.__bases__ if base is not object]
            heritage = f"({', '.join(bases)})" if bases else ""
            return [f"class {name}{heritage}", *self.members(obj)]
        if inspect.isroutine(obj):
            return [self.signature(name, obj)]
        if callable(obj) and not isinstance(obj, types.ModuleType):
            return [f"callable {name}: {self.annotation(type(obj))}"]
        return [f"{name}: {self.annotation(type(obj))} = {self.value(obj)}"]

    def module(self, module_name: str) -> str:
        """One module's heading and every name its ``__all__`` promises."""
        module = importlib.import_module(module_name)
        exported = getattr(module, "__all__", None)
        if exported is None:
            raise SystemExit(
                f"{module_name} is public and declares no __all__; "
                "declare one or rename the module with a leading underscore"
            )
        blocks = ["\n".join(self.render(name, getattr(module, name))) for name in sorted(exported)]
        return f"## {module_name}\n\n" + "\n\n".join(blocks) + "\n"


def render(package: str) -> str:
    """The whole snapshot, header first."""
    renderer = Renderer()
    return HEADER + "\n" + "\n".join(renderer.module(name) for name in module_names(package))


def main(argv: Sequence[str] | None = None) -> int:
    """Print the snapshot, or write it to a file when one is named."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=None, help="file to write instead of stdout")
    parser.add_argument("--package", default="workhorse", help="installed package to read")
    arguments = parser.parse_args(argv)
    snapshot = render(arguments.package)
    if arguments.output is None:
        sys.stdout.write(snapshot)
    else:
        arguments.output.write_text(snapshot, encoding="utf8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
