export { Pool } from "pg";
export {
  attachNotificationPool,
  createProviderAdapter,
  createProviderQueryable,
  createWorkhorseAdapter,
  QueryError,
  rowsToQueryResult,
} from "./adapter.js";
export {
  databaseErrorCode,
  expectOneRow,
  MissingRowError,
  SchemaCompatibilityError,
  WorkhorseError,
} from "./errors.js";
export type { SchemaCompatibilityCode, SchemaCompatibilityVersions } from "./errors.js";
export { WorkhorseMetricsObserver } from "./metrics-observer.js";
export type {
  AdapterNotificationPool,
  ProviderAdapterDefinition,
  ProviderAdapterOptions,
  ProviderQueryableOptions,
  WorkhorseAdapter,
  WorkhorseAdapterOptions,
} from "./adapter.js";
export type {
  ContractSchemaOptions,
  MigrateSchemaOptions,
  MigrateSchemaResult,
  SchemaContractOutcome,
  WorkerClientProtocol,
} from "./schema.js";
export {
  assertSchemaCompatible,
  contractSchema,
  installSchema,
  isMissingDatabaseRelationError,
  MAXIMUM_PROTOCOL_VERSION,
  MAXIMUM_SCHEMA_VERSION,
  migrateSchema,
  MINIMUM_PROTOCOL_VERSION,
  MINIMUM_SCHEMA_VERSION,
  PROTOCOL_VERSION,
  readProtocolVersions,
  readSchemaVersion,
  readWorkerClientProtocols,
  SCHEMA_MIGRATION_LOCK_TIMEOUT_MS,
  WORKHORSE_SCHEMA_BASELINE_VERSION,
  WORKHORSE_SCHEMA_VERSION,
} from "./schema.js";
export {
  assertSupportedPostgres,
  describePostgresSupport,
  MINIMUM_NODE_MAJOR,
  MINIMUM_POSTGRES_MAJOR,
  readPostgresSupport,
  SUPPORTED_NODE_MAJORS,
  SUPPORTED_POSTGRES_MAJORS,
} from "./support.js";
export type { PostgresSupport } from "./support.js";
export {
  MAX_TRACE_CONTEXT_BYTES,
  METRIC_ATTRIBUTE_CARDINALITY_LIMIT,
  registerQueueMetrics,
  registerTelemetryProvider,
  TRACE_ATTRIBUTE_COUNT_LIMIT,
} from "./telemetry.js";
export type {
  QueueMetricSnapshot,
  QueueMetricSource,
  TelemetryAttributes,
  TelemetryAttributeValue,
  TelemetryContext,
  TelemetryCounter,
  TelemetryMetricOptions,
  TelemetryObservation,
  TelemetryObservationDefinition,
  TelemetryRecorder,
  TelemetrySpanKind,
  WorkhorseLogEvent,
  WorkhorseTelemetryProvider,
  WorkhorseTelemetrySpan,
} from "./telemetry.js";
export { Admin, PurgeIdempotencyConflictError } from "./admin.js";
export type {
  AdminAudit,
  PurgeIdempotencyConflictDetails,
  RunTaskNowResult,
  RunTaskNowStatus,
} from "./admin.js";
export {
  CheckpointConflictError,
  CheckpointLeaseLostError,
  ChildConflictError,
  ChildLeaseLostError,
  ChildLimitExceededError,
  ChildResultLimitExceededError,
  DependencyCycleError,
  DependencyLimitExceededError,
  EnqueueIdempotencyConflictError,
  TaskContractValidationError,
  TaskContractUnavailableError,
  TaskValueSizeLimitError,
  Queue,
  ProgressLeaseLostError,
  ProgressRateLimitError,
  RedriveIdempotencyConflictError,
  SignalIdempotencyConflictError,
  SignalWaitConflictError,
  SignalWaitLeaseLostError,
  SignalWaitLimitExceededError,
  HumanWaitAlreadyWaitingError,
  HumanWaitConflictError,
  HumanWaitIdempotencyConflictError,
  HumanWaitLeaseLostError,
  HumanWaitLimitExceededError,
  WaitConflictError,
  WaitLeaseLostError,
  WaitLimitExceededError,
} from "./queue.js";
export type {
  DependencyCycleDetails,
  DependencyLimit,
  MaintenancePhase,
  MaintenancePhaseResult,
  ScheduleWaitRequest,
  ScheduleWaitResult,
  SendSignalRequest,
  SignalDeliveryResult,
  SignalDeliveryStatus,
  SignalWait,
  SignalWaitPage,
  WaitForSignalResult,
  WaitForSignalStatus,
  CompleteHumanWaitRequest,
  HumanWaitCompletionResult,
  HumanWaitCompletionStatus,
  HumanWait,
  HumanWaitPage,
  WaitForHumanResult,
  WaitForHumanStatus,
  ExternalWaitOptions,
  ExternalWaitDeliveryRequest,
  ExternalWaitCursor,
  ExternalWaitQuery,
  ScheduleDefinition,
  ScheduledTask,
  StoredSchedule,
} from "./queue.js";
export {
  CancellationRequestedError,
  DeadlineExceededError,
  ExecutionTimeoutError,
  Worker,
} from "./worker.js";
export type {
  BatchHandler,
  BatchHandlerContext,
  BatchHandlerItem,
  BatchHandlerOutcome,
  BatchHandlerOptions,
  Handler,
  HandlerContext,
  WorkerMaintenanceLoop,
  WorkerMaintenanceTelemetry,
  WorkerOptions,
  WorkerQueueApi,
  WorkerRuntimeState,
} from "./worker.js";
export { defineWorkerProcess, runWorkerProcess, startWorkerProcess } from "./worker-process.js";
export type {
  RunWorkerProcessOptions,
  StartedWorkerProcess,
  WorkerProcessDefinition,
  WorkerProcessLogger,
  WorkerProcessProbeOptions,
  WorkerProcessSignal,
  WorkerProcessSignalSource,
  WorkerProcessWorkerDefinition,
} from "./worker-process.js";
export type {
  BatchExecutionRecord,
  ClaimedTask,
  ChildTask,
  ChildTaskRequest,
  ChildOutcome,
  ChildOutcomes,
  ChildLineage,
  CreateChildResult,
  CreateChildrenResult,
  BulkRedriveOptions,
  BulkRedrivePage,
  CancellationRequest,
  CancelResult,
  CancelStatus,
  ConcurrencyPolicy,
  ConcurrencyPolicyDefinition,
  RateLimit,
  RateLimitPolicy,
  RateLimitPolicyDefinition,
  RateLimitStatus,
  DeadLetter,
  DeadLetterCursor,
  DeadLetterFilter,
  DeadLetterPage,
  DeadLetterQuery,
  DependencyLineage,
  DependencyLineageRecord,
  DependencyTerminalPolicy,
  Dependencies,
  Idempotency,
  Debounce,
  Throttle,
  EnqueueIdempotencyConflictDetails,
  EnqueueIdempotencyConflictField,
  EnqueueNonReplaceableReason,
  EnqueueOutcome,
  EnqueueOptions,
  EnqueueRequest,
  EnqueueResult,
  ExpireOwnedStatus,
  TaskCheckpoint,
  TaskContractVersion,
  TaskTypeContracts,
  TaskProgress,
  TaskAttemptOutcome,
  TaskListCursor,
  TaskListFilter,
  TaskListItem,
  TaskListPage,
  TaskListQuery,
  TaskPayloadProjection,
  TaskPayloadStatus,
  TaskSnapshot,
  TaskState,
  TaskTimelineAttempt,
  TaskTimelineCursor,
  TaskTimelineEntry,
  TaskTimelineEvent,
  TaskTimelinePage,
  TaskTimelineQuery,
  TaskWait,
  HeartbeatStatus,
  Json,
  MaintenancePolicy,
  MaintenancePolicyDefinition,
  MaintenancePolicySetting,
  PolicyValueProvenance,
  Queryable,
  QueueOptions,
  QueueHealth,
  QueueHealthBudgets,
  QueueHealthObservations,
  QueueHealthReason,
  QueueHealthReasonCode,
  QueueHealthStatus,
  RedriveIdempotencyConflictDetails,
  RedriveIdempotencyConflictField,
  RedriveLineage,
  RedriveLineageRecord,
  RedriveRequest,
  RedriveResult,
  RedriveStatus,
  RetryPolicy,
  TraceContext,
  RetentionCategoryValues,
  RetentionPolicy,
  RetentionPolicyDefinition,
  RetentionPolicyImpact,
  RetentionPolicySetting,
  WorkerPauseResult,
  WorkerRegistration,
  WorkerRegistryEntry,
} from "./types.js";
export {
  DEPENDENCY_OPERATIONS_SCAN_LIMIT,
  DEFAULT_IDEMPOTENCY_SCOPE,
  DEFAULT_IDEMPOTENCY_TTL_MS,
  DEFAULT_TASK_QUERY_PAYLOAD_BYTES,
  DEFAULT_TASK_VALUE_MAX_BYTES,
  HEALTH_HISTORY_SCAN_LIMIT,
  MAX_CHECKPOINT_VALUE_BYTES,
  MAX_PROGRESS_VALUE_BYTES,
  MIN_PROGRESS_UPDATE_INTERVAL_MS,
  MAX_CANCELLATION_REASON_CHARACTERS,
  MAX_CANCELLATION_REQUESTED_BY_CHARACTERS,
  MAX_ENQUEUE_BATCH_SIZE,
  MAX_IDEMPOTENCY_KEY_BYTES,
  MAX_IDEMPOTENCY_SCOPE_BYTES,
  MAX_IDEMPOTENCY_TTL_MS,
  MAX_DEBOUNCE_WINDOW_MS,
  MAX_THROTTLE_WINDOW_MS,
  MAX_EXECUTION_TIMEOUT_MS,
  MAX_EXTERNAL_WAIT_ACTOR_CHARACTERS,
  MAX_EXTERNAL_WAIT_IDEMPOTENCY_KEY_BYTES,
  MAX_EXTERNAL_WAIT_LIST_SIZE,
  MAX_EXTERNAL_WAIT_NAME_CHARACTERS,
  MAX_EXTERNAL_WAIT_TIMEOUT_MS,
  MAX_EXTERNAL_WAIT_VALUE_BYTES,
  MAX_EXTERNAL_WAITS_PER_TASK,
  MAX_TASK_QUERY_PAGE_SIZE,
  MAX_TASK_QUERY_PAYLOAD_BYTES,
  MAX_TASK_QUERY_REDACT_KEYS,
  MAX_TASK_PRIORITY,
  MAX_TASK_DEPENDENCIES,
  MAX_TASK_DEPENDENTS,
  MAX_TASK_CONTRACT_SENSITIVE_KEYS,
  MAX_TASK_VALUE_MAX_BYTES,
  MAX_REDRIVE_BATCH_SIZE,
  MAX_REDRIVE_REQUEST_ID_BYTES,
  MAX_WAIT_DURATION_MS,
} from "./types.js";

// Deprecated 0.x names for the ten types Python and Go already agreed on (WH-590).
// Each is a type alias of its replacement and is removed in 1.0.0.
export type {
  EnqueueIdempotency,
  EnqueueDebounce,
  EnqueueThrottle,
  TaskDependencies,
} from "./types.js";
export type {
  SendSignalResult,
  SendSignalStatus,
  CompleteHumanWaitResult,
  CompleteHumanWaitStatus,
  ExternalWaitListOptions,
  ScheduleTaskDefinition,
} from "./queue.js";
