# frozen_string_literal: true

# Renders the public Ruby API of stablemates-workhorse as a stable text snapshot.
#
# ADR 0084 defines the Ruby API as every public constant under Stablemates::Workhorse, plus the
# Active Job adapter, less what carries a +:nodoc:+ marker. This tool reproduces that definition:
# it loads the gem, walks the namespace by reflection, and prints each module's superclass,
# included modules, Data members, constants, and public method signatures.
# +scripts/generate-ruby-api.ts+ writes the result to +api/ruby.txt+, so a removed name or a
# narrowed signature shows up as a deleted or changed line.
#
# Reflection decides what is public, because only the loaded gem knows which constants
# +private_constant+ hid and which methods are private. The source decides the rest: Prism reads
# the +:nodoc:+ comments, which reflection cannot see, and the parameter list as written, because
# +Method#parameters+ drops every default value.

require "prism"
require "active_job"
require "stablemates/workhorse"
require "stablemates/workhorse/active_job"

module ApiSnapshot
  LIB = File.expand_path("../lib", __dir__)
  ROOTS = %w[Stablemates::Workhorse ActiveJob::QueueAdapters::StablematesWorkhorseAdapter].freeze
  # A value that changes on every release rather than with the API.
  UNRENDERED_VALUES = %w[Stablemates::Workhorse::VERSION].freeze
  LITERALS = [String, Symbol, Integer, Float, TrueClass, FalseClass, NilClass].freeze
  # Where each public method that takes +**+ finds the keywords it accepts. The snapshot lists each
  # source, so a keyword a caller could pass has a line. A public +**+ missing here stops the tool.
  KEYWORD_SOURCES = {
    "Stablemates::Workhorse::HandlerContext#run_child" => "Stablemates::Workhorse::EnqueueRequest#initialize",
    "Stablemates::Workhorse::Queue#enqueue" => "Stablemates::Workhorse::EnqueueRequest#initialize",
    "Stablemates::Workhorse::ActiveJob::Options::ClassMethods#workhorse_options" =>
      "Stablemates::Workhorse::ActiveJob::OPTION_KEYS"
  }.freeze
  # A Prism node whose source text is a value, so its whitespace is kept as written.
  LITERAL_NODES = [
    Prism::StringNode, Prism::InterpolatedStringNode, Prism::XStringNode, Prism::InterpolatedXStringNode,
    Prism::SymbolNode, Prism::InterpolatedSymbolNode, Prism::RegularExpressionNode,
    Prism::InterpolatedRegularExpressionNode
  ].freeze

  HEADER = <<~TEXT
    # Public Ruby API
    #
    # Generated by `pnpm ruby-api:generate` from the stablemates-workhorse gem. ADR 0054 and ADR 0084
    # govern this surface: a removed or renamed public constant, method, keyword, or Data member and a
    # narrowed signature are breaking, and an addition is not. A constant or method marked `:nodoc:` is
    # private and absent here, and so is everything under a `:nodoc:` constant.
  TEXT

  # The source facts reflection cannot give: +:nodoc:+ lines and each method's written parameters.
  class Source
    def initialize
      @files = {}
    end

    def nodoc?(location)
      return false if location.nil?

      path, line = location
      internal?(path) && lines(path)[:nodoc].include?(line)
    end

    # The parameter list of the def at +location+ as written, or nil when no def starts there.
    def parameters(location)
      path, line = location
      lines(path)[:defs][line]
    end

    def internal?(path) = !path.nil? && path.start_with?("#{LIB}/")

    private

    def lines(path)
      @files[path] ||= begin
        result = Prism.parse_file(path)
        raise "#{path} does not parse: #{result.errors.map(&:message).join("; ")}" if result.failure?

        nodoc = result.comments.select { |comment| comment.slice.include?(":nodoc:") }
          .map { |comment| comment.location.start_line }
        defs = {}
        visit(result.value) { |node| defs[node.location.start_line] ||= written(node.parameters) }
        {nodoc: nodoc.to_set, defs: defs}
      end
    end

    def visit(node, &block)
      yield node if node.is_a?(Prism::DefNode)
      node.compact_child_nodes.each { |child| visit(child, &block) }
    end

    # The parameter source on one line. Each run of whitespace between tokens becomes one space,
    # and a string, symbol, or regular expression literal keeps its text as written.
    def written(parameters)
      return "" if parameters.nil?

      source = parameters.slice
      base = parameters.location.start_offset
      cursor = 0
      pieces = []
      literals(parameters).each do |node|
        from = node.location.start_offset - base
        pieces << source.byteslice(cursor, from - cursor).gsub(/\s+/, " ") << node.slice
        cursor = node.location.end_offset - base
      end
      pieces << source.byteslice(cursor..).gsub(/\s+/, " ")
      pieces.join.strip
    end

    # The outermost literals under +node+, in source order.
    def literals(node)
      node.compact_child_nodes.flat_map do |child|
        (LITERAL_NODES.any? { |type| child.is_a?(type) }) ? [child] : literals(child)
      end
    end
  end

  class Walker
    def initialize
      @source = Source.new
      @sections = {}
    end

    def run
      ROOTS.each do |name|
        namespace = Object.const_get(name)
        raise "#{name} is not a module" unless namespace.is_a?(Module)

        walk(name, namespace)
      end
      HEADER + @sections.sort.map { |name, lines| "\n#{name}\n#{lines.map { |line| "  #{line}\n" }.join}" }.join
    end

    private

    def walk(name, mod)
      lines = []
      lines.concat(ancestry(mod))
      lines.concat(members(mod))
      mod.constants(false).sort.each do |const|
        next if @source.nodoc?(mod.const_source_location(const))

        full = "#{name}::#{const}"
        value = mod.const_get(const, false)
        if value.is_a?(Module) && value.name == full
          walk(full, value)
        else
          lines << constant(full, const, value)
        end
      end
      lines.concat(methods(mod.singleton_class, "self."))
      lines.concat(constructor(mod)) if mod.is_a?(Class)
      lines.concat(methods(mod, ""))
      @sections["#{mod.is_a?(Class) ? "class" : "module"} #{name}"] = lines
    end

    # The superclass and the modules this module adds to its ancestors. An anonymous superclass,
    # such as the one +Data.define+ returns, stands for its first named ancestor. A module the
    # superclass already has is left out, so a module Ruby prepends to a core class is not listed.
    def ancestry(mod)
      base = mod.is_a?(Class) ? mod.superclass : nil
      base = base.superclass while !base.nil? && base.name.nil?
      lines = (base.nil? || base == Object) ? [] : ["superclass #{base.name}"]
      added = mod.ancestors - [mod] - (base.nil? ? [] : base.ancestors)
      added.each { |included| lines << "include #{included.name}" unless included.is_a?(Class) || included.name.nil? }
      lines
    end

    def members(mod)
      return [] unless mod.is_a?(Class) && mod < Data

      ["members #{mod.members.join(", ")}"]
    end

    def constant(full, const, value)
      return "#{const}: #{value.class.name}" if UNRENDERED_VALUES.include?(full)
      return "#{const} = #{value.inspect}" if literal?(value)
      return "#{const} = #{value.name}" if value.is_a?(Module)

      "#{const}: #{value.class.name}"
    end

    def literal?(value)
      return value.all? { |item| literal?(item) } if value.is_a?(Array)
      return value.all? { |key, item| literal?(key) && literal?(item) } if value.is_a?(Hash)

      LITERALS.any? { |type| value.is_a?(type) }
    end

    def constructor(klass)
      return [] unless klass.private_method_defined?(:initialize, false)

      method = klass.instance_method(:initialize)
      return [] unless @source.internal?(method.source_location&.first)
      return [] if @source.nodoc?(method.source_location)

      ["def initialize#{signature(method)}"]
    end

    def methods(owner, prefix)
      owner.public_instance_methods(false).sort.filter_map do |method_name|
        method = owner.instance_method(method_name)
        next unless @source.internal?(method.source_location&.first)
        next if @source.nodoc?(method.source_location)

        "def #{prefix}#{method_name}#{signature(method)}#{keyword_source(owner, prefix, method)}"
      end
    end

    # The source of the keywords a public +**+ accepts, which KEYWORD_SOURCES must name.
    def keyword_source(owner, prefix, method)
      return "" unless method.parameters.any? { |kind, _| kind == :keyrest }

      owner_name = owner.singleton_class? ? owner.attached_object.name : owner.name
      key = "#{owner_name}#{prefix.empty? ? "#" : "."}#{method.name}"
      source = KEYWORD_SOURCES.fetch(key) do
        raise "#{key} takes ** keywords the snapshot cannot list; name their source in KEYWORD_SOURCES"
      end
      "  # keywords: #{source}"
    end

    def signature(method)
      written = @source.parameters(method.source_location)
      return written.empty? ? "" : "(#{written})" unless written.nil?

      reflected(method.parameters)
    end

    # Parameters for a method no def wrote, such as an +attr_reader+. Defaults are not visible here.
    def reflected(parameters)
      return "" if parameters.empty?

      rendered = parameters.map do |kind, name|
        case kind
        when :req then name.to_s
        when :opt then "#{name} = ..."
        when :rest then "*#{name}"
        when :keyreq then "#{name}:"
        when :key then "#{name}: ..."
        when :keyrest then "**#{name}"
        when :block then "&#{name}"
        end
      end
      "(#{rendered.join(", ")})"
    end
  end
end

$stdout.write(ApiSnapshot::Walker.new.run) if $PROGRAM_NAME == __FILE__
