// Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.

package workhorse

const (
	// ProtocolVersion is the SQL protocol version implemented by this module.
	ProtocolVersion        = 1
	minimumProtocolVersion = 1
	maximumProtocolVersion = 1
	minimumSchemaVersion   = 1
	maximumSchemaVersion   = 1
	// MaxEnqueueBatchSize is PostgreSQL's atomic enqueue batch limit.
	MaxEnqueueBatchSize     = 1000
	defaultJobValueMaxBytes = 1048576
)

var internalStatementRegistry = map[string]string{
	"deregister_worker_v1": `SELECT workhorse.deregister_worker_v1($1::text) AS deregistered`,
	"fire_due_schedules_v1": `SELECT namespace, schedule_name, occurrence_at, job_id
  FROM workhorse.fire_due_schedules_v1($1::text[], $2::timestamptz, $3::integer)`,
	"list_checkpoint":           `SELECT checkpoint_value FROM workhorse.job_checkpoint WHERE job_id = $1::uuid AND checkpoint_name = $2::text`,
	"list_concurrency_policies": `SELECT namespace, queue_name, max_active, max_active_per_key, updated_at FROM workhorse.concurrency_policy, (SELECT $1::text[] AS names) AS filter WHERE cardinality(filter.names) = 0 OR queue_name = ANY(filter.names) ORDER BY queue_name`,
	"list_progress": `SELECT progress_value, revision::text, attempt, fence_token::text,
       worker_id, created_at, updated_at
  FROM workhorse.job_progress
 WHERE job_id = $1::uuid`,
	"list_rate_limit_policies": `SELECT namespace, queue_name, rate_limit, rate_interval_ms, rate_burst, per_key_limit, per_key_interval_ms, per_key_burst, updated_at FROM workhorse.rate_limit_policy, (SELECT $1::text[] AS names) AS filter WHERE cardinality(filter.names) = 0 OR queue_name = ANY(filter.names) ORDER BY queue_name`,
	"promote_v1":               `SELECT workhorse.promote_v1($1::integer) AS promoted`,
	"register_worker_v1": `SELECT workhorse.register_worker_v1(
       $1::text, $2::uuid, $3::text, $4::integer, $5::text[], $6::text[],
       $7::integer, $8::integer, $9::integer, $10::integer, $11::integer,
       $12::integer, $13::integer, $14::integer, $15::boolean
     ) AS paused`,
	"run_maintenance_v1":           `SELECT * FROM workhorse.run_maintenance_v1($1::timestamptz)`,
	"schema_version":               `SELECT version FROM workhorse.schema_version ORDER BY version`,
	"sync_concurrency_policies_v1": `SELECT * FROM workhorse.sync_concurrency_policies_v1($1::text, $2::jsonb, $3::boolean)`,
	"sync_rate_limit_policies_v1":  `SELECT * FROM workhorse.sync_rate_limit_policies_v1($1::text, $2::jsonb, $3::boolean)`,
	"sync_schedule_definitions_v1": `SELECT workhorse.sync_schedule_definitions_v1($1::text, $2::jsonb, $3::boolean)`,
	"tick_v1":                      `SELECT * FROM workhorse.tick_v1($1::integer, $2::integer)`,
	"run_task_now_v1":              `SELECT status, state, run_at FROM workhorse.run_task_now_v1($1::uuid, $2::text, $3::text, $4::text)`,
	"purge_queue_v1":               `SELECT * FROM workhorse.purge_queue_v1($1::text, $2::text, $3::text, $4::text)`,
	"concurrency_policy": `SELECT namespace, queue_name, max_active, max_active_per_key, updated_at
         FROM workhorse.concurrency_policy
        WHERE cardinality($1::text[]) = 0 OR queue_name = ANY($1::text[])
        ORDER BY queue_name`,
	"queue_control":       `SELECT queue_name, paused FROM workhorse.queue_control`,
	"schedule_definition": `SELECT DISTINCT namespace FROM workhorse.schedule_definition ORDER BY namespace`,
	"worker_registry": `SELECT served.queue_name,
               CASE WHEN last_heartbeat_at < clock_timestamp() - interval '30 seconds'
                      THEN 'offline'
                    WHEN draining THEN 'draining'
                    WHEN paused THEN 'paused'
                    ELSE 'running' END AS state,
               count(*)::text AS workers,
               sum(concurrency)::text AS capacity,
               sum(active_slots)::text AS active_slots
          FROM workhorse.worker_registry registry
          CROSS JOIN LATERAL unnest(registry.queue_names) served(queue_name)
         GROUP BY served.queue_name, state
         ORDER BY served.queue_name, state`,
	"sync_rate_limit_policies_v1__queue": `SELECT * FROM workhorse.sync_rate_limit_policies_v1($1, $2::jsonb, $3)`,
	"rate_limit_policy": `SELECT namespace, queue_name, rate_limit, rate_interval_ms, rate_burst,
              per_key_limit, per_key_interval_ms, per_key_burst, updated_at
         FROM workhorse.rate_limit_policy
        WHERE cardinality($1::text[]) = 0 OR queue_name = ANY($1::text[])
        ORDER BY queue_name`,
	"job_checkpoint": `SELECT job_id, checkpoint_name, checkpoint_value, attempt, fence_token::text,
              worker_id, created_at
         FROM workhorse.job_checkpoint
        WHERE job_id = $1::uuid AND checkpoint_name = $2::text`,
	"job_checkpoint__checkpoints_progress_waits": `SELECT job_id, checkpoint_name, checkpoint_value, attempt, fence_token::text,
              worker_id, created_at
         FROM workhorse.job_checkpoint
        WHERE job_id = $1::uuid
        ORDER BY created_at, checkpoint_name`,
	"job_progress": `SELECT job_id, progress_value, revision::text, attempt, fence_token::text,
              worker_id, created_at, updated_at
         FROM workhorse.job_progress
        WHERE job_id = $1::uuid`,
	"job_wait": `SELECT job_id, wait_name, mode, duration_ms::text, requested_wake_at, wake_at,
              attempt, fence_token::text, worker_id, created_at
         FROM workhorse.job_wait
        WHERE job_id = $1::uuid AND wait_name = $2::text`,
	"job_wait__checkpoints_progress_waits": `SELECT job_id, wait_name, mode, duration_ms::text, requested_wake_at, wake_at,
              attempt, fence_token::text, worker_id, created_at
         FROM workhorse.job_wait
        WHERE job_id = $1::uuid
        ORDER BY created_at, wait_name`,
	"schedule_definition__cron_schedules": `SELECT definition.namespace, definition.schedule_name, definition.cron_expression,
              definition.timezone,
              definition.revision::text,
              max(occurrence.occurrence_at) AS last_occurrence_at
         FROM workhorse.schedule_definition definition
         LEFT JOIN workhorse.schedule_occurrence occurrence
           ON occurrence.namespace = definition.namespace
          AND occurrence.schedule_name = definition.schedule_name
        WHERE definition.enabled AND definition.namespace = ANY($1::text[])
        GROUP BY definition.namespace, definition.schedule_name, definition.timezone
        ORDER BY definition.namespace, definition.schedule_name`,
	"fire_schedule_v1": `SELECT workhorse.fire_schedule_v1($1::text, $2::text, $3::bigint, $4::timestamptz) AS job_id`,
	"rate_limit_policy__operator_read_sql": `WITH observed AS (
    SELECT clock_timestamp() AS now
  ), policies AS MATERIALIZED (
    SELECT policy.* FROM workhorse.rate_limit_policy policy
     WHERE cardinality($1::text[]) = 0 OR policy.queue_name = ANY($1::text[])
     ORDER BY policy.queue_name LIMIT 101
  ), queue_status AS (
    SELECT policy.*, observed.now,
           GREATEST(observed.now, COALESCE(bucket.refilled_at, observed.now))
             AS refill_baseline,
           LEAST(policy.rate_burst::numeric, COALESCE(
             bucket.tokens + GREATEST(
               0::numeric,
               extract(epoch FROM observed.now - bucket.refilled_at) * 1000
             ) * policy.rate_limit::numeric / policy.rate_interval_ms::numeric,
             policy.rate_burst::numeric
           )) AS available_tokens
      FROM policies policy CROSS JOIN observed
      LEFT JOIN workhorse.rate_limit_bucket bucket
        ON bucket.queue_name = policy.queue_name
       AND bucket.bucket_scope = 'queue' AND bucket.bucket_key = ''
  )
  SELECT policy.namespace, policy.queue_name, policy.rate_limit,
         policy.rate_interval_ms, policy.rate_burst, policy.per_key_limit,
         policy.per_key_interval_ms, policy.per_key_burst, policy.updated_at,
         policy.available_tokens::text,
         pressure.throttled_ready::text, pressure.throttled_keys::text,
         pressure.next_eligible_at, pressure.sample_capped
         , (SELECT count(*) FROM policies) > 100 AS policy_set_capped
    FROM queue_status policy
    CROSS JOIN LATERAL (
      SELECT count(*) FILTER (WHERE sample.throttled)::integer AS throttled_ready,
             count(DISTINCT sample.concurrency_key) FILTER (
               WHERE sample.key_throttled
             )::integer AS throttled_keys,
             min(sample.eligible_at) FILTER (WHERE sample.throttled) AS next_eligible_at,
             count(*) > 100 AS sample_capped
        FROM (
          SELECT ready.concurrency_key,
                 policy.available_tokens < 1 OR keyed.available_tokens < 1 AS throttled,
                 keyed.available_tokens < 1 AS key_throttled,
                 CASE WHEN policy.available_tokens < 1 OR keyed.available_tokens < 1 THEN
                   GREATEST(
                     CASE WHEN policy.available_tokens < 1 THEN
                       policy.refill_baseline + make_interval(
                       secs => CEIL(
                         (1 - policy.available_tokens) * policy.rate_interval_ms::numeric
                         / policy.rate_limit::numeric
                       )::double precision / 1000
                     ) END,
                     CASE WHEN keyed.available_tokens < 1 THEN
                       keyed.refill_baseline + make_interval(
                       secs => CEIL(
                         (1 - keyed.available_tokens) * policy.per_key_interval_ms::numeric
                         / policy.per_key_limit::numeric
                       )::double precision / 1000
                     ) END
                   )
                 END AS eligible_at
            FROM (
              SELECT runtime.concurrency_key
                FROM workhorse.job_runtime runtime
               WHERE runtime.state = 'ready' AND runtime.queue_name = policy.queue_name
               ORDER BY runtime.sequence, runtime.job_id LIMIT 101
            ) ready
            CROSS JOIN LATERAL (
              SELECT CASE
                WHEN policy.per_key_limit IS NULL OR ready.concurrency_key IS NULL THEN 1
                ELSE LEAST(policy.per_key_burst::numeric, COALESCE(
                  bucket.tokens + GREATEST(
                    0::numeric,
                    extract(epoch FROM policy.now - bucket.refilled_at) * 1000
                  ) * policy.per_key_limit::numeric / policy.per_key_interval_ms::numeric,
                  policy.per_key_burst::numeric
                ))
              END AS available_tokens,
              CASE
                WHEN policy.per_key_limit IS NULL OR ready.concurrency_key IS NULL
                  THEN policy.now
                ELSE GREATEST(policy.now, COALESCE(bucket.refilled_at, policy.now))
              END AS refill_baseline
              FROM (SELECT true) present
              LEFT JOIN workhorse.rate_limit_bucket bucket
                ON bucket.queue_name = policy.queue_name
               AND bucket.bucket_scope = 'key'
               AND bucket.bucket_key = ready.concurrency_key
            ) keyed
        ) sample
    ) pressure
   ORDER BY policy.queue_name LIMIT 100`,
	"list_jobs_v1": `SELECT listed.job_id, listed.queue_name, listed.job_type, listed.concurrency_key,
              listed.priority, listed.tags, listed.state, dependency.prerequisite_job_id,
              dependency.prerequisite_job_ids, dependency.on_success AS dependency_on_success,
              dependency.on_failure AS dependency_on_failure,
              dependency.on_cancellation AS dependency_on_cancellation,
              CASE WHEN listed.state = 'blocked' THEN 'prerequisite_pending' END AS blocked_reason,
              parent_edge.parent_job_id, children.child_job_ids,
              listed.current_attempt, listed.max_attempts, listed.retry_policy,
              listed.deadline_at,
              listed.execution_timeout_ms::text AS execution_timeout_ms,
              listed.run_at, listed.cancel_requested_at, listed.cancel_requested_by,
              listed.cancel_reason, listed.created_at, listed.updated_at, listed.payload,
              listed.payload_status, listed.payload_bytes, listed.has_more,
              listed.cursor_created_at::text AS cursor_created_at, listed.cursor_signature
         FROM workhorse.list_jobs_v1(
           $1::jsonb, $2::integer, $3::timestamptz, $4::uuid, $5::text, $6::jsonb
         ) listed
         LEFT JOIN LATERAL (
           SELECT CASE WHEN count(*) = 1
                    THEN (array_agg(edge.prerequisite_job_id))[1] END AS prerequisite_job_id,
                  COALESCE(array_agg(edge.prerequisite_job_id ORDER BY edge.prerequisite_job_id)
                    FILTER (WHERE edge.prerequisite_job_id IS NOT NULL), '{}') AS prerequisite_job_ids,
                  min(edge.on_success) AS on_success,
                  min(edge.on_failure) AS on_failure,
                  min(edge.on_cancellation) AS on_cancellation
             FROM workhorse.job_dependency edge
            WHERE edge.dependent_job_id = listed.job_id
         ) dependency ON true
         LEFT JOIN workhorse.job_child parent_edge ON parent_edge.child_job_id = listed.job_id
         LEFT JOIN LATERAL (
           SELECT COALESCE(array_agg(edge.child_job_id ORDER BY edge.child_job_id)
                    FILTER (WHERE edge.child_job_id IS NOT NULL), '{}') AS child_job_ids
             FROM workhorse.job_child edge WHERE edge.parent_job_id = listed.job_id
         ) children ON true`,
	"list_job_timeline_v1": `SELECT kind, record_id::text AS record_id, priority, attempt, event_type, details,
              fence_token::text AS fence_token, worker_id, outcome, started_at, claimed_at,
              finished_at, error, occurred_at, has_more,
              cursor_occurred_at::text AS cursor_occurred_at
         FROM workhorse.list_job_timeline_v1(
           $1::uuid, $2::integer, $3::timestamptz, $4::text, $5::bigint
         )`,
	"list_dead_letters_v1": `SELECT * FROM workhorse.list_dead_letters_v1($1::jsonb, $2::integer, $3::timestamptz, $4::uuid)`,
	"redrive_v1":           `SELECT * FROM workhorse.redrive_v1($1::uuid, $2::text, $3::text, $4::text)`,
	"redrive_many_v1":      `SELECT status, source_job_id, target_job_id, source_state, target_state, requested_at, source_finished_at_cursor, has_more FROM workhorse.redrive_many_v1($1::jsonb, $2::integer, $3::boolean, $4::text, $5::text, $6::text, $7::timestamptz, $8::uuid) ORDER BY ordinal`,
	"redrive_lineage_v1":   `SELECT * FROM workhorse.redrive_lineage_v1($1::uuid, $2::integer)`,
	"job_dependency": `SELECT dependent_job_id, prerequisite_job_id, on_success, on_failure, on_cancellation,
              created_at, released_at, resolution
         FROM workhorse.job_dependency
        WHERE dependent_job_id = $1::uuid OR prerequisite_job_id = $1::uuid
        ORDER BY dependent_job_id, prerequisite_job_id
        LIMIT $2::integer`,
	"job_child": `SELECT edge.parent_job_id, edge.child_job_id, edge.child_name,
              child.job_type AS child_type, edge.created_at, edge.joined_at,
              outcome.state AS outcome_state, outcome.error AS outcome_error
         FROM workhorse.job_child edge
         JOIN workhorse.job child ON child.id = edge.child_job_id
         LEFT JOIN workhorse.job_outcome outcome ON outcome.job_id = edge.child_job_id
        WHERE edge.parent_job_id = $1::uuid OR edge.child_job_id = $1::uuid
        ORDER BY edge.created_at, edge.parent_job_id, edge.child_job_id
        LIMIT $2::integer`,
	"redact_top_level_keys_v1": `SELECT j.id, j.queue_name, j.job_type, j.concurrency_key, j.priority,
              workhorse.redact_top_level_keys_v1(j.payload, j.payload_redact_keys) AS payload,
              j.contract_version, j.tags, j.retry_policy,
              j.deadline_at, j.execution_timeout_ms::text,
              COALESCE(r.state, o.state) AS state,
              dependency.prerequisite_job_id,
              dependency.prerequisite_job_ids,
              dependency.on_success AS dependency_on_success,
              dependency.on_failure AS dependency_on_failure,
              dependency.on_cancellation AS dependency_on_cancellation,
              CASE WHEN r.state = 'blocked' THEN 'prerequisite_pending' END AS blocked_reason,
              parent_edge.parent_job_id, children.child_job_ids,
              COALESCE(r.current_attempt, o.current_attempt) AS current_attempt,
              j.max_attempts, COALESCE(r.fence_token, o.fence_token) AS version,
              COALESCE(r.run_at, o.run_at) AS run_at,
              workhorse.redact_top_level_keys_v1(o.result, j.result_redact_keys) AS result,
              COALESCE(r.error, o.error) AS error, r.cancel_requested_at,
              r.cancel_requested_by, r.cancel_reason,
              p.progress_value, p.revision::text AS progress_revision,
              p.attempt AS progress_attempt, p.fence_token::text AS progress_fence_token,
              p.worker_id AS progress_worker_id, p.created_at AS progress_created_at,
              p.updated_at AS progress_updated_at, j.created_at,
              COALESCE(r.updated_at, o.updated_at) AS updated_at
         FROM workhorse.job j
         LEFT JOIN workhorse.job_runtime r ON r.job_id = j.id
         LEFT JOIN workhorse.job_outcome o ON o.job_id = j.id
         LEFT JOIN LATERAL (
           SELECT CASE WHEN count(*) = 1
                    THEN (array_agg(edge.prerequisite_job_id))[1] END AS prerequisite_job_id,
                  COALESCE(array_agg(edge.prerequisite_job_id ORDER BY edge.prerequisite_job_id)
                    FILTER (WHERE edge.prerequisite_job_id IS NOT NULL), '{}') AS prerequisite_job_ids,
                  min(edge.on_success) AS on_success,
                  min(edge.on_failure) AS on_failure,
                  min(edge.on_cancellation) AS on_cancellation
             FROM workhorse.job_dependency edge
            WHERE edge.dependent_job_id = j.id
         ) dependency ON true
         LEFT JOIN workhorse.job_child parent_edge ON parent_edge.child_job_id = j.id
         LEFT JOIN LATERAL (
           SELECT COALESCE(array_agg(edge.child_job_id ORDER BY edge.child_job_id)
                    FILTER (WHERE edge.child_job_id IS NOT NULL), '{}') AS child_job_ids
             FROM workhorse.job_child edge WHERE edge.parent_job_id = j.id
         ) children ON true
         LEFT JOIN workhorse.job_progress p ON p.job_id = j.id
        WHERE j.id = $1::uuid`,
	"promote_v1__queue_administration":          `SELECT workhorse.promote_v1($1::integer) AS count`,
	"set_queue_paused_v1":                       `SELECT workhorse.set_queue_paused_v1($1::text, true, $2::text, $3::text, $4::text)`,
	"set_queue_paused_v1__queue_administration": `SELECT workhorse.set_queue_paused_v1($1::text, false, $2::text, $3::text, $4::text)`,
	"prepare_history_partitions_v1":             `SELECT * FROM workhorse.prepare_history_partitions_v1($1::boolean, $2::timestamptz)`,
	"rollup_stats_v1":                           `SELECT * FROM workhorse.rollup_stats_v1($1::boolean, $2::timestamptz, $3::integer)`,
	"retain_history_v1":                         `SELECT * FROM workhorse.retain_history_v1($1::boolean, $2::timestamptz)`,
	"prune_terminal_storage_v1":                 `SELECT * FROM workhorse.prune_terminal_storage_v1($1::boolean, $2::timestamptz)`,
	"sync_retention_policy_v1": `SELECT (policy).* FROM workhorse.sync_retention_policy_v1(
         $1::integer, $2::integer, $3::integer, $4::integer, $5::integer,
         $6::integer, $7::integer, $8::integer, $9::integer, $10::integer,
         $11::integer, $12::boolean
       ) policy`,
	"override_retention_policy_v1": `SELECT (policy).* FROM workhorse.override_retention_policy_v1($1::jsonb) policy`,
	"revert_retention_policy_v1":   `SELECT (policy).* FROM workhorse.revert_retention_policy_v1($1::text[]) policy`,
	"retention_policy_preview": `SELECT
        (SELECT count(*)::integer FROM (
          SELECT 1 FROM workhorse.job job
          JOIN workhorse.job_outcome outcome ON outcome.job_id = job.id
          WHERE $1::integer IS NOT NULL AND $2::integer IS NOT NULL
            AND job.created_at < clock_timestamp() - make_interval(days => $1)
            AND outcome.finished_at < clock_timestamp() - make_interval(days => $2)
          LIMIT 10001
        ) rows) AS terminal_jobs,
        (SELECT count(*)::integer FROM (
          SELECT 1 FROM workhorse.job_event
          WHERE $3::integer IS NOT NULL
            AND occurred_at < clock_timestamp() - make_interval(days => $3)
          LIMIT 10001
        ) rows) AS job_events,
        (SELECT count(*)::integer FROM (
          SELECT 1 FROM workhorse.attempt_history
          WHERE $4::integer IS NOT NULL
            AND occurred_at < clock_timestamp() - make_interval(days => $4)
          LIMIT 10001
        ) rows) AS attempt_history,
        (SELECT count(*)::integer FROM (
          SELECT 1 FROM workhorse.schedule_occurrence
          WHERE $5::integer IS NOT NULL
            AND occurrence_at < clock_timestamp() - make_interval(days => $5)
          LIMIT 10001
        ) rows) AS schedule_occurrences,
        (SELECT count(*)::integer FROM (
          SELECT 1 FROM workhorse.job_stat_bucket
          WHERE $6::integer IS NOT NULL
            AND bucket_start < clock_timestamp() - make_interval(days => $6)
          UNION ALL
          SELECT 1 FROM workhorse.job_stat_bucket_hour
          WHERE $6::integer IS NOT NULL
            AND bucket_start < clock_timestamp() - make_interval(days => $6)
          UNION ALL
          SELECT 1 FROM workhorse.job_stat_bucket_day
          WHERE $6::integer IS NOT NULL
            AND bucket_start < clock_timestamp() - make_interval(days => $6)
          LIMIT 10001
        ) rows) AS statistics`,
	"get_retention_policy_v1": `SELECT (policy).* FROM workhorse.get_retention_policy_v1() policy`,
	"sync_maintenance_policy_v1": `SELECT (policy).* FROM workhorse.sync_maintenance_policy_v1(
         $1::text, $2::integer, $3::integer, $4::time, $5::integer, $6::integer, $7::integer,
         $8::boolean
       ) policy`,
	"override_maintenance_policy_v1": `SELECT (policy).* FROM workhorse.override_maintenance_policy_v1(
         $1::text, $2::integer, $3::integer, $4::time, $5::integer, $6::integer, $7::integer
       ) policy`,
	"revert_maintenance_policy_v1": `SELECT (policy).* FROM workhorse.revert_maintenance_policy_v1($1::text[]) policy`,
	"get_maintenance_policy_v1":    `SELECT (policy).* FROM workhorse.get_maintenance_policy_v1() policy`,
	"set_worker_paused_v1":         `SELECT * FROM workhorse.set_worker_paused_v1($1::text, $2::boolean, $3::text, $4::text, $5::text)`,
	"worker_registry__worker_registry": `SELECT worker_id, instance_id, hostname, pid, queue_names, schedule_namespaces, queue_name, concurrency, active_slots, draining, paused, paused_by,
              paused_reason, paused_at, started_at, last_heartbeat_at
         FROM workhorse.worker_registry
        ORDER BY last_heartbeat_at DESC, worker_id`,
	"prune_worker_registry_v1": `SELECT workhorse.prune_worker_registry_v1(make_interval(secs => $1::double precision)) AS count`,
	"protocol_version":         `SELECT version FROM workhorse.protocol_version ORDER BY version`,
	"schema_installation_probe": `SELECT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'workhorse') AS schema_exists,
           to_regclass('workhorse.schema_version') IS NOT NULL AS version_table_exists,
           EXISTS (
             SELECT 1
               FROM unnest(ARRAY['job_current', 'ready_job', 'scheduled_job', 'lease'])
                 AS legacy(relation_name)
              WHERE to_regclass(format('workhorse.%I', relation_name)) IS NOT NULL
           ) AS legacy_relation_exists`,
	"metrics_observer": `
        WITH queue_names AS (
          SELECT queue_name FROM workhorse.job_runtime
          UNION
          SELECT queue_name FROM workhorse.queue_control
        ), depth AS (
          SELECT names.queue_name,
         count(runtime.job_id) FILTER (WHERE runtime.state = 'scheduled')::text AS scheduled,
         count(runtime.job_id) FILTER (WHERE runtime.state = 'ready')::text AS ready,
         count(runtime.job_id) FILTER (WHERE runtime.state = 'active')::text AS active,
         extract(epoch FROM clock_timestamp() - min(runtime.ready_at) FILTER (
       WHERE runtime.state = 'ready'
     )) * 1000 AS oldest_ready_age_ms,
         count(runtime.job_id) FILTER (
       WHERE runtime.state = 'active' AND runtime.expires_at <= clock_timestamp()
     )::text AS expired,
         count(runtime.job_id) FILTER (
       WHERE runtime.deadline_at IS NOT NULL AND runtime.deadline_at <= clock_timestamp()
     )::text AS overdue_deadlines,
         count(runtime.job_id) FILTER (
       WHERE runtime.state = 'active' AND runtime.attempt_timeout_at <= clock_timestamp()
     )::text AS overdue_execution_timeouts
      FROM queue_names names
      LEFT JOIN workhorse.job_runtime runtime
        ON runtime.queue_name = names.queue_name
     GROUP BY names.queue_name
        )
        SELECT depth.*, coalesce(control.paused, false) AS paused,
               waits.pending_signal_waits, waits.pending_human_waits,
               waits.overdue_signal_waits, waits.overdue_human_waits,
               waits.rejected_signals, waits.rejected_human_waits
          FROM depth
          LEFT JOIN workhorse.queue_control control USING (queue_name)
          CROSS JOIN LATERAL (
            SELECT
              (SELECT count(*)::text FROM (
                SELECT 1 FROM workhorse.job_signal_wait signal
                 JOIN workhorse.job_runtime runtime ON runtime.job_id = signal.job_id
                WHERE runtime.queue_name = depth.queue_name
                  AND runtime.state = 'scheduled' AND runtime.wait_name = signal.signal_name
                  AND runtime.current_attempt = signal.attempt AND signal.delivered_at IS NULL
                LIMIT 10001
              ) sampled) AS pending_signal_waits,
              (SELECT count(*)::text FROM (
                SELECT 1 FROM workhorse.job_human_wait human_wait
                 JOIN workhorse.job_runtime runtime ON runtime.job_id = human_wait.job_id
                WHERE runtime.queue_name = depth.queue_name
                  AND runtime.state = 'scheduled' AND runtime.wait_name = human_wait.token_name
                  AND runtime.current_attempt = human_wait.attempt
                  AND human_wait.completed_at IS NULL
                LIMIT 10001
              ) sampled) AS pending_human_waits,
              (SELECT count(*)::text FROM (
                SELECT 1 FROM workhorse.job_signal_wait signal
                 JOIN workhorse.job_runtime runtime ON runtime.job_id = signal.job_id
                WHERE runtime.queue_name = depth.queue_name
                  AND runtime.state = 'scheduled' AND runtime.wait_name = signal.signal_name
                  AND runtime.current_attempt = signal.attempt AND signal.delivered_at IS NULL
                  AND runtime.deadline_at <= clock_timestamp()
                LIMIT 10001
              ) sampled) AS overdue_signal_waits,
              (SELECT count(*)::text FROM (
                SELECT 1 FROM workhorse.job_human_wait human_wait
                 JOIN workhorse.job_runtime runtime ON runtime.job_id = human_wait.job_id
                WHERE runtime.queue_name = depth.queue_name
                  AND runtime.state = 'scheduled' AND runtime.wait_name = human_wait.token_name
                  AND runtime.current_attempt = human_wait.attempt
                  AND human_wait.completed_at IS NULL
                  AND runtime.deadline_at <= clock_timestamp()
                LIMIT 10001
              ) sampled) AS overdue_human_waits,
              (SELECT count(*)::text FROM (
                SELECT 1 FROM workhorse.job_event event
                 JOIN workhorse.job job ON job.id = event.job_id
                WHERE job.queue_name = depth.queue_name AND event.event_type = 'signal_rejected'
                  AND event.occurred_at >= $1::timestamptz
                LIMIT 10001
              ) sampled) AS rejected_signals,
              (SELECT count(*)::text FROM (
                SELECT 1 FROM workhorse.job_event event
                 JOIN workhorse.job job ON job.id = event.job_id
                WHERE job.queue_name = depth.queue_name
                  AND event.event_type = 'human_wait_rejected'
                  AND event.occurred_at >= $1::timestamptz
                LIMIT 10001
              ) sampled) AS rejected_human_waits
          ) waits
         ORDER BY depth.queue_name`,
	"queue_metric_snapshot": `WITH queue_names AS (
         SELECT $1::text AS queue_name
         UNION SELECT queue_name FROM workhorse.job_runtime
         UNION SELECT queue_name FROM workhorse.queue_control
         UNION SELECT queue_name FROM workhorse.concurrency_policy
         UNION SELECT queue_name FROM workhorse.rate_limit_policy
         UNION SELECT unnest(queue_names) FROM workhorse.worker_registry
         UNION SELECT query.queue_name FROM workhorse.job_query query
          JOIN workhorse.job_outcome outcome ON outcome.job_id = query.job_id
         WHERE outcome.state = 'failed' AND outcome.error->>'name' = 'DependencyFailed'
         UNION SELECT query.queue_name FROM workhorse.job_query query
          JOIN workhorse.job_child edge ON edge.parent_job_id = query.job_id
       ), usage AS (
         SELECT names.queue_name,
         count(runtime.job_id) FILTER (WHERE runtime.state = 'ready')::text AS ready,
         count(runtime.job_id) FILTER (WHERE runtime.state = 'scheduled')::text AS scheduled,
         count(runtime.job_id) FILTER (WHERE runtime.state = 'active')::text AS active,
         count(runtime.job_id) FILTER (
       WHERE runtime.state = 'active' AND runtime.expires_at > clock_timestamp()
     )::text AS concurrency_active,
         extract(epoch FROM clock_timestamp() - min(runtime.ready_at) FILTER (
       WHERE runtime.state = 'ready'
     )) * 1000 AS oldest_ready_age_ms
      FROM queue_names names
      LEFT JOIN workhorse.job_runtime runtime
        ON runtime.queue_name = names.queue_name
     GROUP BY names.queue_name
       )
       SELECT usage.*, policy.max_active,
              COALESCE(blocked.blocked_ready, 0)::text AS blocked_ready,
              LEAST(dependencies.blocked_jobs, 10000)::text
                AS dependency_blocked,
              LEAST(dependencies.pending_edges, 10000)::text
                AS dependency_pending_edges,
              LEAST(dependencies.failed_resolutions, 10000)::text
               AS dependency_failed_resolutions,
             dependencies.blocked_jobs > 10000
               OR dependencies.pending_edges > 10000
               OR dependencies.failed_resolutions > 10000
               AS dependency_counts_capped,
              LEAST(children.waiting_parents, 10000)::text
             AS child_waiting_parents,
           LEAST(children.pending_children, 10000)::text
             AS child_pending_children,
           LEAST(children.unjoined_results, 10000)::text
             AS child_unjoined_results,
           LEAST(children.failed_parents, 10000)::text
             AS child_failed_parents,
           LEAST(children.canceled_parents, 10000)::text
             AS child_canceled_parents,
           children.waiting_parents > 10000
             OR children.pending_children > 10000
             OR children.unjoined_results > 10000
             OR children.failed_parents > 10000
             OR children.canceled_parents > 10000
             AS child_counts_capped
         FROM usage
         LEFT JOIN workhorse.concurrency_policy policy ON policy.queue_name = usage.queue_name
         LEFT JOIN LATERAL (
           SELECT count(*) FILTER (
                    WHERE usage.concurrency_active::integer >= policy.max_active
                       OR (
                         policy.max_active_per_key IS NOT NULL
                         AND sample.concurrency_key IS NOT NULL
                         AND sample.key_active >= policy.max_active_per_key
                       )
                  )::integer AS blocked_ready
             FROM (
               SELECT ready.concurrency_key,
                      (SELECT count(*)::integer FROM workhorse.job_runtime active
                        WHERE active.state = 'active'
                          AND active.queue_name = usage.queue_name
                          AND active.concurrency_key = ready.concurrency_key
                          AND active.expires_at > clock_timestamp()) AS key_active
                 FROM workhorse.job_runtime ready
                WHERE ready.state = 'ready' AND ready.queue_name = usage.queue_name
                ORDER BY ready.sequence, ready.job_id LIMIT 100
             ) sample
         ) blocked ON policy.queue_name IS NOT NULL
         CROSS JOIN LATERAL (
           SELECT
             (SELECT count(*) FROM (
               SELECT 1 FROM workhorse.job_runtime runtime
                WHERE runtime.queue_name = usage.queue_name AND runtime.state = 'blocked'
                LIMIT 10001
             ) sampled_blocked)
               AS blocked_jobs,
             (SELECT count(*) FROM (
               SELECT 1 FROM workhorse.job_dependency edge
                JOIN workhorse.job_runtime runtime ON runtime.job_id = edge.dependent_job_id
               WHERE runtime.queue_name = usage.queue_name AND runtime.state = 'blocked'
                 AND edge.released_at IS NULL
               LIMIT 10001
             ) sampled_pending)
               AS pending_edges,
             (SELECT count(*) FROM (
               SELECT 1 FROM workhorse.job_outcome outcome
                JOIN workhorse.job_query query ON query.job_id = outcome.job_id
               WHERE query.queue_name = usage.queue_name AND outcome.state = 'failed'
                 AND outcome.error->>'name' = 'DependencyFailed'
               LIMIT 10001
             ) sampled_failed) AS failed_resolutions
         ) dependencies
         CROSS JOIN LATERAL (

    SELECT
      (SELECT count(*) FROM (
        SELECT 1 FROM workhorse.job_runtime runtime
         WHERE runtime.queue_name = usage.queue_name AND runtime.state = 'blocked'
           AND EXISTS (
             SELECT 1 FROM workhorse.job_child edge WHERE edge.parent_job_id = runtime.job_id
           )
         LIMIT 10001
      ) sampled_waiting) AS waiting_parents,
      (SELECT count(*) FROM (
        SELECT 1 FROM workhorse.job_child edge
        JOIN workhorse.job_query parent ON parent.job_id = edge.parent_job_id
         WHERE parent.queue_name = usage.queue_name AND edge.joined_at IS NULL
           AND NOT EXISTS (
             SELECT 1 FROM workhorse.job_outcome outcome WHERE outcome.job_id = edge.child_job_id
           )
         LIMIT 10001
      ) sampled_pending) AS pending_children,
      (SELECT count(*) FROM (
        SELECT 1 FROM workhorse.job_child edge
        JOIN workhorse.job_query parent ON parent.job_id = edge.parent_job_id
         JOIN workhorse.job_outcome outcome ON outcome.job_id = edge.child_job_id
        WHERE parent.queue_name = usage.queue_name AND edge.joined_at IS NULL AND outcome.state = 'succeeded'
         LIMIT 10001
      ) sampled_unjoined) AS unjoined_results,
      (SELECT count(*) FROM (
        SELECT 1 FROM workhorse.job_outcome outcome
        JOIN workhorse.job_query parent ON parent.job_id = outcome.job_id
         WHERE parent.queue_name = usage.queue_name AND outcome.state = 'failed'
           AND outcome.error->>'name' = 'DependencyFailed'
           AND EXISTS (
             SELECT 1 FROM workhorse.job_child edge WHERE edge.parent_job_id = outcome.job_id
           )
         LIMIT 10001
      ) sampled_failed) AS failed_parents,
      (SELECT count(*) FROM (
        SELECT 1 FROM workhorse.job_outcome outcome
        JOIN workhorse.job_query parent ON parent.job_id = outcome.job_id
         WHERE parent.queue_name = usage.queue_name AND outcome.state = 'canceled'
           AND outcome.error->>'name' = 'DependencyCanceled'
           AND EXISTS (
             SELECT 1 FROM workhorse.job_child edge WHERE edge.parent_job_id = outcome.job_id
           )
         LIMIT 10001
      ) sampled_canceled) AS canceled_parents
         ) children
        ORDER BY usage.queue_name`,
	"postgres_support": `SELECT current_setting('server_version_num') AS number,
            current_setting('server_version') AS version`,
}

var protocolStatementRegistry = map[string]string{
	"acknowledge_cancel_v1":        `SELECT workhorse.acknowledge_cancel_v1($1::uuid, $2::text, $3::bigint) AS accepted`,
	"cancel_v1":                    `SELECT status, state, current_attempt, requested_at, requested_by, reason, finished_at FROM workhorse.cancel_v1($1::uuid, $2::text, $3::text)`,
	"claim_many_v1":                `SELECT * FROM workhorse.claim_many_v1($1::text, $2::text, $3::integer, $4::integer)`,
	"claim_v1":                     `SELECT * FROM workhorse.claim_v1($1::text, $2::text, $3::integer)`,
	"complete_human_wait_v1":       `SELECT status, result, completed_at, completed_by FROM workhorse.complete_human_wait_v1($1::uuid, $2::text, $3::jsonb, $4::text, $5::text)`,
	"complete_v1":                  `SELECT workhorse.complete_v1($1::uuid, $2::text, $3::bigint, $4::jsonb) AS accepted`,
	"create_child_v1":              `SELECT status, child_job_id, child_type, created_at, joined_at, result FROM workhorse.create_child_v1($1::uuid, $2::text, $3::bigint, $4::text, $5::jsonb)`,
	"create_children_v1":           `SELECT status, children, results, result_bytes, result_limit_bytes FROM workhorse.create_children_v1($1::uuid, $2::text, $3::bigint, $4::jsonb, $5::text)`,
	"dashboard_human_wait_v1":      `SELECT job_id, queue_name, job_type, token_name AS wait_name, context, attempt, created_at, deadline_at, created_at::text AS cursor_created_at FROM workhorse.dashboard_human_wait_v1 WHERE ($2::timestamptz IS NULL OR (created_at, job_id, token_name) > ($2::timestamptz, $3::uuid, $4::text)) ORDER BY created_at, job_id, token_name LIMIT $1::integer`,
	"dashboard_signal_wait_v1":     `SELECT job_id, queue_name, job_type, signal_name AS wait_name, attempt, created_at, deadline_at, created_at::text AS cursor_created_at FROM workhorse.dashboard_signal_wait_v1 WHERE ($2::timestamptz IS NULL OR (created_at, job_id, signal_name) > ($2::timestamptz, $3::uuid, $4::text)) ORDER BY created_at, job_id, signal_name LIMIT $1::integer`,
	"enqueue_many_v1":              `SELECT ordinal, job_id, outcome, reason FROM workhorse.enqueue_many_v1($1::jsonb) ORDER BY ordinal`,
	"expire_owned_telemetry_v1":    `SELECT * FROM workhorse.expire_owned_telemetry_v1($1::uuid, $2::text, $3::bigint)`,
	"fail_v1":                      `SELECT workhorse.fail_v1($1::uuid, $2::text, $3::bigint, $4::jsonb, $5::integer) AS state`,
	"get_contract_definition_v1":   `SELECT (definition).* FROM workhorse.get_contract_definition_v1($1::text, $2::text) definition`,
	"heartbeat_many_v1":            `SELECT job_id::text AS job_id, status FROM workhorse.heartbeat_many_v1($1::text, $2::jsonb) ORDER BY ordinal`,
	"heartbeat_v1":                 `SELECT workhorse.heartbeat_v1($1::uuid, $2::text, $3::bigint, $4::integer) AS status`,
	"queue_health_v1":              `SELECT workhorse.queue_health_v1($1::timestamptz) AS snapshot`,
	"record_batch_dispatch_v1":     `SELECT workhorse.record_batch_dispatch_v1($1::uuid, $2::uuid[], $3::integer[], $4::bigint[], $5::text) AS recorded`,
	"record_batch_failure_v1":      `SELECT workhorse.record_batch_failure_v1($1::uuid, $2::uuid[], $3::integer[], $4::bigint[], $5::text) AS recorded`,
	"recover_expired_telemetry_v1": `SELECT * FROM workhorse.recover_expired_telemetry_v1($1::integer, $2::integer)`,
	"run_maintenance_v1":           `SELECT * FROM workhorse.run_maintenance_v1($1::timestamptz)`,
	"save_checkpoint_v1":           `SELECT status, checkpoint_value, attempt, fence_token::text, worker_id, created_at FROM workhorse.save_checkpoint_v1($1::uuid, $2::text, $3::bigint, $4::text, $5::jsonb)`,
	"schedule_wait_v1":             `SELECT status, wait_name, mode, duration_ms::text, requested_wake_at, wake_at, attempt, fence_token::text, worker_id, created_at FROM workhorse.schedule_wait_v1($1::uuid, $2::text, $3::bigint, $4::text, $5::bigint, $6::timestamptz)`,
	"send_signal_v1":               `SELECT status, payload, delivered_at, delivered_by FROM workhorse.send_signal_v1($1::uuid, $2::text, $3::jsonb, $4::text, $5::text)`,
	"sync_contract_definitions_v1": `SELECT workhorse.sync_contract_definitions_v1($1::jsonb)`,
	"update_progress_v1":           `SELECT status, progress_value, revision::text, attempt, fence_token::text, worker_id, created_at, updated_at, retry_after_ms::text FROM workhorse.update_progress_v1($1::uuid, $2::text, $3::bigint, $4::jsonb)`,
	"wait_for_human_v1":            `SELECT status, result FROM workhorse.wait_for_human_v1($1::uuid, $2::text, $3::bigint, $4::text, $5::jsonb, $6::bigint)`,
	"wait_for_signal_v1":           `SELECT status, payload FROM workhorse.wait_for_signal_v1($1::uuid, $2::text, $3::bigint, $4::text, $5::bigint)`,
}

var adminStatementRegistry = map[string]string{
	"get_checkpoint": `SELECT job_id::text job_id,checkpoint_name,checkpoint_value,attempt,fence_token::text fence_token,worker_id,created_at FROM workhorse.job_checkpoint WHERE job_id=$1::uuid AND checkpoint_name=$2::text`,
	"get_job": `SELECT j.id::text AS id, j.queue_name, j.job_type, j.concurrency_key, j.priority,
              workhorse.redact_top_level_keys_v1(j.payload, j.payload_redact_keys) AS payload,
              j.contract_version, j.tags, j.retry_policy, j.deadline_at,
              j.execution_timeout_ms::text, COALESCE(r.state, o.state) AS state,
              dependency.prerequisite_job_id, dependency.prerequisite_job_ids,
              dependency.on_success AS dependency_on_success,
              dependency.on_failure AS dependency_on_failure,
              dependency.on_cancellation AS dependency_on_cancellation,
              CASE WHEN r.state = 'blocked' THEN 'prerequisite_pending' END AS blocked_reason,
              parent_edge.parent_job_id, children.child_job_ids,
              COALESCE(r.current_attempt, o.current_attempt) AS current_attempt, j.max_attempts,
              COALESCE(r.fence_token, o.fence_token)::text AS version,
              COALESCE(r.run_at, o.run_at) AS run_at,
              workhorse.redact_top_level_keys_v1(o.result, j.result_redact_keys) AS result,
              COALESCE(r.error, o.error) AS error, r.cancel_requested_at,
              r.cancel_requested_by, r.cancel_reason, p.progress_value,
              p.revision::text AS progress_revision, p.attempt AS progress_attempt,
              p.fence_token::text AS progress_fence_token, p.worker_id AS progress_worker_id,
              p.created_at AS progress_created_at, p.updated_at AS progress_updated_at,
              j.created_at, COALESCE(r.updated_at, o.updated_at) AS updated_at
         FROM workhorse.job j
         LEFT JOIN workhorse.job_runtime r ON r.job_id = j.id
         LEFT JOIN workhorse.job_outcome o ON o.job_id = j.id
         LEFT JOIN LATERAL (
           SELECT CASE WHEN count(*) = 1 THEN (array_agg(edge.prerequisite_job_id))[1] END
                    AS prerequisite_job_id,
                  COALESCE(array_agg(edge.prerequisite_job_id ORDER BY edge.prerequisite_job_id)
                    FILTER (WHERE edge.prerequisite_job_id IS NOT NULL), '{}')
                    AS prerequisite_job_ids,
                  min(edge.on_success) AS on_success, min(edge.on_failure) AS on_failure,
                  min(edge.on_cancellation) AS on_cancellation
             FROM workhorse.job_dependency edge WHERE edge.dependent_job_id = j.id
         ) dependency ON true
         LEFT JOIN workhorse.job_child parent_edge ON parent_edge.child_job_id = j.id
         LEFT JOIN LATERAL (
           SELECT COALESCE(array_agg(edge.child_job_id ORDER BY edge.child_job_id)
                    FILTER (WHERE edge.child_job_id IS NOT NULL), '{}') AS child_job_ids
             FROM workhorse.job_child edge WHERE edge.parent_job_id = j.id
         ) children ON true
         LEFT JOIN workhorse.job_progress p ON p.job_id = j.id
        WHERE j.id = $1::uuid`,
	"get_progress":      `SELECT job_id::text job_id,progress_value,revision::text revision,attempt,fence_token::text fence_token,worker_id,created_at,updated_at FROM workhorse.job_progress WHERE job_id=$1::uuid`,
	"get_wait":          `SELECT job_id::text job_id,wait_name,mode,duration_ms::text duration_ms,requested_wake_at,wake_at,attempt,fence_token::text fence_token,worker_id,created_at FROM workhorse.job_wait WHERE job_id=$1::uuid AND wait_name=$2::text`,
	"list_checkpoints":  `SELECT job_id::text job_id,checkpoint_name,checkpoint_value,attempt,fence_token::text fence_token,worker_id,created_at FROM workhorse.job_checkpoint WHERE job_id=$1::uuid ORDER BY created_at,checkpoint_name`,
	"list_dead_letters": `SELECT job_id::text job_id,queue_name,job_type,concurrency_key,priority,payload,tags,current_attempt,max_attempts,retry_policy,deadline_at,execution_timeout_ms,error,finished_at,redrive_count,has_more,cursor_finished_at FROM workhorse.list_dead_letters_v1($1::jsonb,$2::integer,$3::timestamptz,$4::uuid)`,
	"list_human_waits": `WITH parameters AS (
         SELECT $1::integer AS page_limit, $2::timestamptz AS cursor_created_at,
                $3::uuid AS cursor_job_id, $4::text AS cursor_name
       )
       SELECT job_id::text AS job_id, queue_name, job_type, token_name AS wait_name, context, attempt,
              created_at, deadline_at, created_at::text AS cursor_created_at
         FROM workhorse.dashboard_human_wait_v1, parameters
        WHERE parameters.cursor_created_at IS NULL OR (created_at, job_id, token_name) >
              (parameters.cursor_created_at, parameters.cursor_job_id, parameters.cursor_name)
        ORDER BY created_at, job_id, token_name LIMIT (SELECT page_limit FROM parameters)`,
	"list_job_timeline": `SELECT kind,record_id::text record_id,priority,attempt,event_type,details,fence_token::text fence_token,worker_id,outcome,started_at,claimed_at,finished_at,error,occurred_at,has_more,cursor_occurred_at::text cursor_occurred_at FROM workhorse.list_job_timeline_v1($1::uuid,$2::integer,$3::timestamptz,$4::text,$5::bigint)`,
	"list_jobs": `SELECT listed.job_id::text AS job_id, listed.queue_name, listed.job_type, listed.concurrency_key,
              listed.priority, listed.tags, listed.state, dependency.prerequisite_job_id,
              dependency.prerequisite_job_ids, dependency.on_success AS dependency_on_success,
              dependency.on_failure AS dependency_on_failure,
              dependency.on_cancellation AS dependency_on_cancellation,
              CASE WHEN listed.state = 'blocked' THEN 'prerequisite_pending' END AS blocked_reason,
              parent_edge.parent_job_id, children.child_job_ids, listed.current_attempt,
              listed.max_attempts, listed.retry_policy, listed.deadline_at,
              listed.execution_timeout_ms::text AS execution_timeout_ms, listed.run_at,
              listed.cancel_requested_at, listed.cancel_requested_by, listed.cancel_reason,
              listed.created_at, listed.updated_at, listed.payload, listed.payload_status,
              listed.payload_bytes, listed.has_more,
              listed.cursor_created_at::text AS cursor_created_at, listed.cursor_signature
         FROM workhorse.list_jobs_v1(
           $1::jsonb, $2::integer, $3::timestamptz, $4::uuid, $5::text, $6::jsonb
         ) listed
         LEFT JOIN LATERAL (
           SELECT CASE WHEN count(*) = 1 THEN (array_agg(edge.prerequisite_job_id))[1] END
                    AS prerequisite_job_id,
                  COALESCE(array_agg(edge.prerequisite_job_id ORDER BY edge.prerequisite_job_id)
                    FILTER (WHERE edge.prerequisite_job_id IS NOT NULL), '{}')
                    AS prerequisite_job_ids,
                  min(edge.on_success) AS on_success, min(edge.on_failure) AS on_failure,
                  min(edge.on_cancellation) AS on_cancellation
             FROM workhorse.job_dependency edge
            WHERE edge.dependent_job_id = listed.job_id
         ) dependency ON true
         LEFT JOIN workhorse.job_child parent_edge ON parent_edge.child_job_id = listed.job_id
         LEFT JOIN LATERAL (
           SELECT COALESCE(array_agg(edge.child_job_id ORDER BY edge.child_job_id)
                    FILTER (WHERE edge.child_job_id IS NOT NULL), '{}') AS child_job_ids
             FROM workhorse.job_child edge WHERE edge.parent_job_id = listed.job_id
         ) children ON true`,
	"list_signal_waits": `WITH parameters AS (
         SELECT $1::integer AS page_limit, $2::timestamptz AS cursor_created_at,
                $3::uuid AS cursor_job_id, $4::text AS cursor_name
       )
       SELECT job_id::text AS job_id, queue_name, job_type, signal_name AS wait_name, attempt, created_at,
              deadline_at, created_at::text AS cursor_created_at
         FROM workhorse.dashboard_signal_wait_v1, parameters
        WHERE parameters.cursor_created_at IS NULL OR (created_at, job_id, signal_name) >
              (parameters.cursor_created_at, parameters.cursor_job_id, parameters.cursor_name)
        ORDER BY created_at, job_id, signal_name LIMIT (SELECT page_limit FROM parameters)`,
	"list_waits":       `SELECT job_id::text job_id,wait_name,mode,duration_ms::text duration_ms,requested_wake_at,wake_at,attempt,fence_token::text fence_token,worker_id,created_at FROM workhorse.job_wait WHERE job_id=$1::uuid ORDER BY created_at,wait_name`,
	"list_workers":     `SELECT worker_id,instance_id,hostname,pid,queue_names,schedule_namespaces,queue_name,concurrency,active_slots,draining,paused,paused_by,paused_reason,paused_at,started_at,last_heartbeat_at FROM workhorse.worker_registry ORDER BY last_heartbeat_at DESC,worker_id`,
	"purge_queue":      `SELECT deleted_count FROM workhorse.purge_queue_v1($1::text,$2::text,$3::text,$4::text)`,
	"redrive":          `SELECT status,source_job_id::text source_job_id,target_job_id::text target_job_id,source_state,target_state,requested_at FROM workhorse.redrive_v1($1::uuid,$2::text,$3::text,$4::text)`,
	"redrive_many":     `SELECT status,source_job_id::text source_job_id,target_job_id::text target_job_id,source_state,target_state,requested_at,source_finished_at_cursor,has_more FROM workhorse.redrive_many_v1($1::jsonb,$2::integer,$3::boolean,$4::text,$5::text,$6::text,$7::timestamptz,$8::uuid) ORDER BY ordinal`,
	"set_queue_paused": `SELECT workhorse.set_queue_paused_v1($1::text,$2::boolean,$3::text,$4::text,$5::text)`,
	"set_worker_paused": `SELECT * FROM workhorse.set_worker_paused_v1(
         $1::text, $2::boolean, $3::text, $4::text, $5::text)`,
	"current_database": `SELECT current_database() AS database`,
}
