import { readdir, readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import path from "node:path";
import ts from "typescript";
import {
  assertPythonStatementBindings,
  findPythonStatementAccesses,
  type PythonSource,
} from "./sql-catalogue-python-bindings.js";
import { parseSqlSchema } from "./sql-surface.js";
import {
  classifyGovernedSurface,
  deriveGovernedSurface,
  formatFindings,
  mergeGovernedSurface,
  readSurfaceSources,
  type GovernedSurface,
} from "./sql-governed-surface.js";

type Catalogue = "internal" | "protocol" | "admin";
type Statement = {
  name: string;
  arity: number;
  contract: string;
  catalogues: Catalogue[];
  pythonBinding?: string;
};
type Manifest = {
  protocolVersion: number;
  schema: { installedVersion: number; minimumVersion: number; maximumVersion: number };
  supportedClientProtocol: { minimumVersion: number; maximumVersion: number };
  limits: { defaultJobValueMaxBytes: number; maxEnqueueBatchSize: number };
  statements?: Statement[];
  [key: string]: unknown;
};

const repository = path.resolve(import.meta.dirname, "..");
const manifestPath = path.join(repository, "protocol/v1/manifest.json");
const check = process.argv.includes("--check");
const typescriptOnly = process.argv.includes("--typescript-only");
const acceptBreaking = process.argv.includes("--accept-breaking");

const governedSurfacePath = path.join(repository, "protocol/v1/governed-surface.json");

const breakingGuidance =
  "A supported release reads these, so removing or retyping one narrows workhorse.protocol_version " +
  "(ADR 0053, ADR 0054). Add a _vN beside the predecessor instead, or take the break deliberately " +
  "with --accept-breaking.";

function arity(sql: string): number {
  return Math.max(0, ...Array.from(sql.matchAll(/\$(\d+)/g), (match) => Number(match[1])));
}

function goString(value: string): string {
  return `\`${value.replaceAll("`", '` + "`" + `')}\``;
}

function pythonString(value: string): string {
  return JSON.stringify(value);
}

function renderGo(manifest: Manifest, statements: Statement[]): string {
  const groups = (["internal", "protocol", "admin"] as const).map((catalogue) => {
    const entries = statements
      .filter((item) => item.catalogues.includes(catalogue))
      .map((item) => `\t${JSON.stringify(item.name)}: ${goString(item.contract)},`)
      .join("\n");
    return `var ${catalogue}StatementRegistry = map[string]string{\n${entries}\n}`;
  });
  const source = `// Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.\n\npackage workhorse\n\nconst (\n\t// ProtocolVersion is the SQL protocol version implemented by this module.\n\tProtocolVersion = ${manifest.protocolVersion}\n\tminimumProtocolVersion = ${manifest.supportedClientProtocol.minimumVersion}\n\tmaximumProtocolVersion = ${manifest.supportedClientProtocol.maximumVersion}\n\tminimumSchemaVersion = ${manifest.schema.minimumVersion}\n\tmaximumSchemaVersion = ${manifest.schema.maximumVersion}\n\t// MaxEnqueueBatchSize is PostgreSQL's atomic enqueue batch limit.\n\tMaxEnqueueBatchSize = ${manifest.limits.maxEnqueueBatchSize}\n\tdefaultJobValueMaxBytes = ${manifest.limits.defaultJobValueMaxBytes}\n)\n\n${groups.join("\n\n")}\n`;
  return execFileSync("gofmt", { input: source, encoding: "utf8" });
}

function renderTypeScript(manifest: Manifest, statements: Statement[]): string {
  const entries = statements
    .map((item) => `  ${JSON.stringify(item.name)}: ${JSON.stringify(item.contract)},`)
    .join("\n");
  const source = `// Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.\nexport const PROTOCOL_VERSION = ${manifest.protocolVersion};\nexport const MINIMUM_PROTOCOL_VERSION = ${manifest.supportedClientProtocol.minimumVersion};\nexport const MAXIMUM_PROTOCOL_VERSION = ${manifest.supportedClientProtocol.maximumVersion};\nexport const WORKHORSE_SCHEMA_BASELINE_VERSION = ${manifest.schema.minimumVersion};\nexport const WORKHORSE_SCHEMA_VERSION = ${manifest.schema.installedVersion};\nexport const MINIMUM_SCHEMA_VERSION = ${manifest.schema.minimumVersion};\nexport const MAXIMUM_SCHEMA_VERSION = ${manifest.schema.maximumVersion};\nexport const DEFAULT_JOB_VALUE_MAX_BYTES = ${manifest.limits.defaultJobValueMaxBytes};\nexport const MAX_ENQUEUE_BATCH_SIZE = ${manifest.limits.maxEnqueueBatchSize};\n\nexport const SQL_STATEMENTS = {\n${entries}\n} as const;\n`;
  return execFileSync("pnpm", ["exec", "oxfmt", "--stdin-filepath=sql-catalogue.generated.ts"], {
    cwd: repository,
    input: source,
    encoding: "utf8",
  });
}

function renderPython(
  manifest: Manifest,
  statements: Statement[],
  pythonBindings: Record<string, string>,
): string {
  const entries = statements
    .map((item) => {
      const psycopg = item.contract.replace(/\$\d+/g, "%s");
      return `    ${pythonString(item.name)}: (${pythonString(psycopg)}, ${pythonString(item.contract)}),`;
    })
    .join("\n");
  const fields = Object.keys(pythonBindings)
    .map((name) => `    ${name}: DriverStatement`)
    .join("\n");
  const values = Object.entries(pythonBindings)
    .map(([field, name]) => `    ${field}=_statement(${pythonString(name)}),`)
    .join("\n");
  const source = `# Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.\n# ruff: noqa: E501\n\nfrom __future__ import annotations\n\nfrom dataclasses import dataclass\nfrom typing import Literal\n\nPROTOCOL_VERSION = ${manifest.protocolVersion}\nMINIMUM_PROTOCOL_VERSION = ${manifest.supportedClientProtocol.minimumVersion}\nMAXIMUM_PROTOCOL_VERSION = ${manifest.supportedClientProtocol.maximumVersion}\nMINIMUM_SCHEMA_VERSION = ${manifest.schema.minimumVersion}\nMAXIMUM_SCHEMA_VERSION = ${manifest.schema.maximumVersion}\nDEFAULT_VALUE_MAX_BYTES = ${manifest.limits.defaultJobValueMaxBytes}\nMAX_BATCH_SIZE = ${manifest.limits.maxEnqueueBatchSize}\n\nDriverDialect = Literal["psycopg", "asyncpg"]\n\n\n@dataclass(frozen=True)\nclass DriverStatement:\n    psycopg: str\n    asyncpg: str\n\n    def for_dialect(self, dialect: DriverDialect) -> str:\n        return self.psycopg if dialect == "psycopg" else self.asyncpg\n\n\nSQL_STATEMENTS: dict[str, tuple[str, str]] = {\n${entries}\n}\n\n\ndef _statement(name: str) -> DriverStatement:\n    psycopg, asyncpg = SQL_STATEMENTS[name]\n    return DriverStatement(psycopg=psycopg, asyncpg=asyncpg)\n\n\n@dataclass(frozen=True)\nclass StatementRegistry:\n${fields}\n\n\nSTATEMENTS = StatementRegistry(\n${values}\n)\n`;
  return execFileSync("uv", ["run", "--project", "python", "ruff", "format", "-"], {
    cwd: repository,
    input: source,
    encoding: "utf8",
  });
}

async function readPythonSources(): Promise<PythonSource[]> {
  const sourceRoot = path.join(repository, "python/src/workhorse");
  const sources: PythonSource[] = [];

  async function inspect(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        await inspect(filename);
        continue;
      }
      if (!entry.name.endsWith(".py") || filename === path.join(sourceRoot, "_statements.py")) {
        continue;
      }
      sources.push({
        filename: path.relative(repository, filename),
        source: await readFile(filename, "utf8"),
      });
    }
  }

  await inspect(sourceRoot);
  return sources;
}

/**
 * Classify the governed SQL surface against the promise, then emit the widened promise.
 *
 * `--check` never writes: a breaking change fails by name, and an addition reports that the
 * artifact is stale so `pnpm sql-catalogues:generate` can record it.
 */
async function governSqlSurface(): Promise<void> {
  const schema = parseSqlSchema(
    await readFile(path.join(repository, "sql/schema/current.sql"), "utf8"),
  );
  const current = deriveGovernedSurface(schema, await readSurfaceSources(repository));
  const committed = await readFile(governedSurfacePath, "utf8").catch(() => null);
  const promised: GovernedSurface =
    committed === null
      ? {
          formatVersion: 1,
          functions: {},
          relations: {},
          internalHelpers: { functions: [], relations: [] },
        }
      : (JSON.parse(committed) as GovernedSurface);

  const findings = classifyGovernedSurface(promised, current);
  if (findings.length > 0 && !acceptBreaking) {
    throw new Error(
      `The governed SQL surface has breaking changes:\n${formatFindings(findings)}\n\n${breakingGuidance}`,
    );
  }
  // `protocol/v1/*.json` is inside the formatted set, so the artifact is written the way
  // `pnpm format:check` expects rather than the way JSON.stringify indents.
  const contents = execFileSync(
    "pnpm",
    ["exec", "oxfmt", "--stdin-filepath=governed-surface.json"],
    {
      cwd: repository,
      input: `${JSON.stringify(acceptBreaking ? current : mergeGovernedSurface(promised, current), null, 2)}\n`,
      encoding: "utf8",
    },
  );
  if (check) {
    if (committed !== contents) {
      throw new Error(
        "protocol/v1/governed-surface.json is stale; the change is additive. Run pnpm sql-catalogues:generate",
      );
    }
    return;
  }
  await writeFile(governedSurfacePath, contents);
}

async function emit(relative: string, contents: string): Promise<void> {
  const filename = path.join(repository, relative);
  if (check) {
    const current = await readFile(filename, "utf8").catch(() => "");
    if (current !== contents)
      throw new Error(`${relative} is stale; run pnpm sql-catalogues:generate`);
    return;
  }
  await writeFile(filename, contents);
}

async function assertNoInlineTypeScriptSql(): Promise<void> {
  const sourceRoot = path.join(repository, "typescript/core/src");
  const allowedDynamicSql = new Set(["cli/reset-db.ts", "notifications.ts"]);
  const violations: string[] = [];

  async function inspect(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        await inspect(filename);
        continue;
      }
      if (!entry.name.endsWith(".ts") || entry.name.endsWith(".generated.ts")) continue;
      const relative = path.relative(sourceRoot, filename);
      if (allowedDynamicSql.has(relative)) continue;
      const source = await readFile(filename, "utf8");
      const sourceFile = ts.createSourceFile(filename, source, ts.ScriptTarget.Latest, true);
      function visit(node: ts.Node): void {
        if (
          ts.isCallExpression(node) &&
          ts.isPropertyAccessExpression(node.expression) &&
          node.expression.name.text === "query" &&
          node.arguments[0] !== undefined &&
          (ts.isStringLiteral(node.arguments[0]) ||
            ts.isTemplateExpression(node.arguments[0]) ||
            ts.isNoSubstitutionTemplateLiteral(node.arguments[0]))
        ) {
          const line =
            sourceFile.getLineAndCharacterOfPosition(node.arguments[0].getStart()).line + 1;
          violations.push(`${path.relative(repository, filename)}:${line}`);
        }
        ts.forEachChild(node, visit);
      }
      visit(sourceFile);
    }
  }

  await inspect(sourceRoot);
  if (violations.length > 0) {
    throw new Error(`TypeScript SQL must come from SQL_STATEMENTS:\n${violations.join("\n")}`);
  }
}

const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as Manifest;
if (!manifest.statements?.length) throw new Error("manifest statements catalogue is empty");
const names = new Set<string>();
const pythonBindings: Record<string, string> = {};
for (const statement of manifest.statements) {
  if (names.has(statement.name)) throw new Error(`duplicate statement ${statement.name}`);
  names.add(statement.name);
  if (arity(statement.contract) !== statement.arity)
    throw new Error(`${statement.name} has the wrong arity`);
  if (statement.pythonBinding !== undefined) {
    if (Object.hasOwn(pythonBindings, statement.pythonBinding))
      throw new Error(`duplicate Python statement binding ${statement.pythonBinding}`);
    pythonBindings[statement.pythonBinding] = statement.name;
  }
}
if (check) await assertNoInlineTypeScriptSql();
await governSqlSurface();
const outputs = [
  emit(
    "typescript/core/src/queue/sql-catalogue.generated.ts",
    renderTypeScript(manifest, manifest.statements),
  ),
];
if (!typescriptOnly) {
  const pythonSources = await readPythonSources();
  const pythonAccesses = findPythonStatementAccesses(
    pythonSources,
    path.join(repository, "python"),
  );
  assertPythonStatementBindings(pythonBindings, names, pythonAccesses);
  outputs.push(
    emit("go/sql_catalogue_generated.go", renderGo(manifest, manifest.statements)),
    emit(
      "python/src/workhorse/_statements.py",
      renderPython(manifest, manifest.statements, pythonBindings),
    ),
  );
}
await Promise.all(outputs);
