import { writeOrCheck } from "./api-snapshot.js";
import { apiEntries, renderApi } from "./typescript-api.js";

/**
 * Write or verify `api/typescript.txt`.
 *
 * The snapshot is read from the built declarations, so `pnpm build:runtime:dev` must have run in
 * this checkout first. CI's `static` job builds before it checks for the same reason.
 */

const header = [
  "# Public TypeScript API",
  "#",
  "# Generated by `pnpm typescript-api:generate` from the shipped declarations of every published",
  "# package. ADR 0054 governs this surface: a removed or renamed name and a narrowed type are",
  "# breaking, and an addition is not. Entry points list what each `exports` subpath reaches, and",
  "# declarations follow once each. A declaration a dependency owns is named without its members,",
  "# because it moves with that dependency range instead.",
  "",
].join("\n");

await writeOrCheck(
  {
    path: "api/typescript.txt",
    generateCommand: "pnpm typescript-api:generate",
    meaning: "A gone line is a removal, a rename, or a narrowing, and ADR 0054 makes it breaking.",
    goneLabel: "gone",
    arrivedLabel: "arrived",
  },
  `${header}\n${renderApi(await apiEntries())}`,
  process.argv.includes("--check"),
);
