import { spawn } from "node:child_process";
import path from "node:path";

import { writeOrCheck } from "./api-snapshot.js";
import { repositoryRoot } from "./packages.js";

/**
 * Write or verify `api/rust.txt`, the public API of the `workhorse` crate.
 *
 * ADR 0079 governs the crate's public items and its feature names. A feature can gate public items,
 * so one build cannot describe the surface: an item moved behind a feature vanishes from a default
 * build while an all-features build still shows it. The snapshot therefore reads the crate once
 * with no features and once per feature, and prefixes every item a feature adds with that feature's
 * `cfg`. Moving an item behind a feature then changes its line, which the check reports as gone.
 *
 * `rust/tools/api-snapshot` does the reading from rustdoc JSON. Stable rustdoc writes that format
 * only when `RUSTC_BOOTSTRAP` unlocks `-Z unstable-options`, and the pinned toolchain decides the
 * format version the tool reads, so the environment variable is set for the rustdoc run alone.
 */

const check = process.argv.includes("--check");
const crate = "workhorse";
// A target directory of its own, because the rustdoc runs set `RUSTC_BOOTSTRAP` and would otherwise
// invalidate the fingerprints of every ordinary build that shares `target/`.
const targetDirectory = path.join("target", "api");

const header = [
  "# Public Rust API",
  "#",
  "# Generated by `pnpm rust-api:generate`. ADR 0079 governs this surface: a gone line is a",
  "# removal, a rename, a narrowing, or an item moved behind a feature, and each is breaking. An",
  "# arrived line is an addition. `pnpm rust-api:check` fails on either, so an addition costs one",
  "# regeneration. Blanket impls are omitted because each follows from a bound listed here.",
  "",
].join("\n");

async function run(
  command: string,
  args: readonly string[],
  environment: NodeJS.ProcessEnv = process.env,
): Promise<string> {
  return await new Promise<string>((resolve, reject) => {
    const child = spawn(command, [...args], {
      cwd: repositoryRoot,
      env: environment,
      stdio: ["ignore", "pipe", "inherit"],
    });
    let output = "";
    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk: string) => {
      output += chunk;
    });
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (code === 0) resolve(output);
      else reject(new Error(`${command} ${args.join(" ")} exited with ${signal ?? String(code)}`));
    });
  });
}

/** The crate's declared features, sorted, read from Cargo rather than from a list kept here. */
async function features(): Promise<string[]> {
  const metadata = JSON.parse(
    await run("cargo", ["metadata", "--format-version", "1", "--no-deps", "--locked"]),
  ) as { packages: { name: string; features: Record<string, string[]> }[] };
  const found = metadata.packages.find((candidate) => candidate.name === crate);
  if (found === undefined) throw new Error(`cargo metadata lists no ${crate} package`);
  return Object.keys(found.features)
    .filter((name) => name !== "default")
    .toSorted();
}

/** Every public item of one build of the crate, one per line, in the tool's order. */
async function items(enabled: readonly string[]): Promise<string[]> {
  await run(
    "cargo",
    [
      "rustdoc",
      "--quiet",
      "--locked",
      "--package",
      crate,
      "--target-dir",
      targetDirectory,
      ...(enabled.length === 0 ? [] : ["--features", enabled.join(",")]),
      "--",
      "-Z",
      "unstable-options",
      "--output-format",
      "json",
    ],
    { ...process.env, RUSTC_BOOTSTRAP: "1" },
  );
  const output = await run("cargo", [
    "run",
    "--quiet",
    "--locked",
    "--package",
    "workhorse-api-snapshot",
    "--target-dir",
    targetDirectory,
    "--",
    path.join(targetDirectory, "doc", `${crate}.json`),
  ]);
  return output.split("\n").filter((line) => line !== "");
}

/** Lines of `after` that `before` does not hold, counting repeats, in `after`'s order. */
function added(before: readonly string[], after: readonly string[]): string[] {
  const remaining = new Map<string, number>();
  for (const line of before) remaining.set(line, (remaining.get(line) ?? 0) + 1);
  return after.filter((line) => {
    const count = remaining.get(line) ?? 0;
    if (count === 0) return true;
    remaining.set(line, count - 1);
    return false;
  });
}

const declared = await features();
const base = await items([]);
// One line per feature, so removing one is a gone line and adding one is only an arrived line.
const lines = [...declared.map((feature) => `feature ${feature}`), "", ...base];
const contributed = new Set(base);
for (const feature of declared) {
  const alone = await items([feature]);
  const removed = added(alone, base);
  if (removed.length > 0) {
    throw new Error(
      `Enabling ${feature} removes public items, which this snapshot cannot describe: ${removed[0]}`,
    );
  }
  const cfg = `#[cfg(feature = "${feature}")]`;
  const extra = added(base, alone);
  for (const line of extra) contributed.add(line);
  const section = extra.length === 0 ? ["adds no public items"] : extra;
  lines.push("", ...section.map((line) => `${cfg} ${line}`));
}
// Two features together could add an item neither adds alone. Refusing keeps that from going
// ungoverned; the day it happens, the snapshot needs a section for the combination.
const combined = (await items(declared)).filter((line) => !contributed.has(line));
if (combined.length > 0) {
  throw new Error(
    `Enabling every feature adds items no single feature adds, which this snapshot cannot describe: ${combined[0]}`,
  );
}

await writeOrCheck(
  {
    path: "api/rust.txt",
    generateCommand: "pnpm rust-api:generate",
    meaning:
      "A gone line is a removal, a rename, a narrowing, or an item moved behind a feature, and ADR 0079 makes it breaking.",
    goneLabel: "gone",
    arrivedLabel: "arrived",
  },
  `${header}\n${lines.join("\n")}\n`,
  check,
);
