import { writeOrCheck } from "./api-snapshot.js";
import { renderCliSurface } from "./cli-surface.js";

/**
 * Write or verify `api/cli.txt`.
 *
 * The snapshot is read from the built CLI declaration, so `pnpm build:runtime:dev` must have run in
 * this checkout first. CI's `static` job builds before it checks for the same reason.
 */

const header = [
  "# The workhorse CLI surface",
  "#",
  "# Generated by `pnpm cli-surface:generate` from typescript/core/src/cli/surface.ts, which the",
  "# CLI itself dispatches, parses, and serializes through. ADR 0054 governs this surface: a",
  "# removed or renamed command or flag is breaking, so is a changed exit code meaning, and so is a",
  "# removed or retyped `--json` field. An addition is not. The CLI's help text is not governed and",
  "# is not read here.",
  "",
].join("\n");

await writeOrCheck(
  {
    path: "api/cli.txt",
    generateCommand: "pnpm cli-surface:generate",
    meaning:
      "A gone line removes or renames something a script already invokes or parses, which fails" +
      " only when that script next runs.",
    goneLabel: "gone",
    arrivedLabel: "arrived",
  },
  `${header}\n${await renderCliSurface()}`,
  process.argv.includes("--check"),
);
