import { writeOrCheck } from "./api-snapshot.js";
import { renderTelemetry, telemetrySurface } from "./telemetry-surface.js";

/**
 * Write or verify `api/telemetry.txt`.
 *
 * The snapshot is read from the emitting source rather than from a build, so this check needs no
 * compiled output and no database.
 */

const header = [
  "# Telemetry names",
  "#",
  "# Generated by `pnpm telemetry-surface:generate` from the source that emits them. ADR 0054",
  "# governs this surface and ADR 0048 places it in the OpenTelemetry adapter: a removed or renamed",
  "# instrument, span, or attribute is breaking, as is a changed unit or kind, and an addition is",
  "# not. Log event names are not listed, because WorkhorseLogEvent is an exported union and",
  "# api/typescript.txt already prints every member.",
  "",
].join("\n");

await writeOrCheck(
  {
    path: "api/telemetry.txt",
    generateCommand: "pnpm telemetry-surface:generate",
    meaning:
      "A gone line renames or removes a name a dashboard, an alert, and a query already match on," +
      " which no compiler reports and no consumer can adapt to silently. Renaming one is a major" +
      " release in TypeScript, Python, and Go at once, because the cross-language catalogue keeps" +
      " the three emitting the same names.",
    goneLabel: "gone",
    arrivedLabel: "arrived",
  },
  `${header}\n${renderTelemetry(await telemetrySurface())}`,
  process.argv.includes("--check"),
);
