import { readdir, readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import path from "node:path";
import ts from "typescript";
import {
  assertPythonStatementBindings,
  findPythonStatementAccesses,
  type PythonSource,
} from "./sql-catalogue-python-bindings.js";

type Catalogue = "internal" | "protocol" | "admin";
type Statement = { name: string; arity: number; contract: string; catalogues: Catalogue[] };
type Manifest = { statements?: Statement[]; [key: string]: unknown };

const repository = path.resolve(import.meta.dirname, "..");
const manifestPath = path.join(repository, "protocol/v1/manifest.json");
const check = process.argv.includes("--check");

const pythonBindings: Record<string, string> = {
  compatibility: "schema_version",
  health: "queue_health_v1",
  cancel: "cancel_v1",
  enqueue_many: "enqueue_many_v1",
  sync_concurrency_policies: "sync_concurrency_policies_v1",
  list_concurrency_policies: "list_concurrency_policies",
  sync_rate_limit_policies: "sync_rate_limit_policies_v1",
  list_rate_limit_policies: "list_rate_limit_policies",
  sync_schedules: "sync_schedule_definitions_v1",
  sync_contracts: "sync_contract_definitions_v1",
  get_contract: "get_contract_definition_v1",
  tick: "tick_v1",
  run_maintenance: "run_maintenance_v1",
  register_worker: "register_worker_v1",
  deregister_worker: "deregister_worker_v1",
  fire_due_schedules: "fire_due_schedules_v1",
  promote: "promote_v1",
  recover_expired: "recover_expired_telemetry_v1",
  claim_many: "claim_many_v1",
  record_batch_dispatch: "record_batch_dispatch_v1",
  record_batch_failure: "record_batch_failure_v1",
  heartbeat_many: "heartbeat_many_v1",
  expire_owned: "expire_owned_telemetry_v1",
  acknowledge_cancel: "acknowledge_cancel_v1",
  complete: "complete_v1",
  fail: "fail_v1",
  list_checkpoints: "list_checkpoints",
  save_checkpoint: "save_checkpoint_v1",
  list_progress: "list_progress",
  update_progress: "update_progress_v1",
  list_waits: "list_waits",
  schedule_wait: "schedule_wait_v1",
  wait_for_signal: "wait_for_signal_v1",
  send_signal: "send_signal_v1",
  wait_for_human: "wait_for_human_v1",
  complete_human_wait: "complete_human_wait_v1",
  create_child: "create_child_v1",
  create_children: "create_children_v1",
};

function arity(sql: string): number {
  return Math.max(0, ...Array.from(sql.matchAll(/\$(\d+)/g), (match) => Number(match[1])));
}

function goString(value: string): string {
  return `\`${value.replaceAll("`", '` + "`" + `')}\``;
}

function pythonString(value: string): string {
  return JSON.stringify(value);
}

function renderGo(statements: Statement[]): string {
  const groups = (["internal", "protocol", "admin"] as const).map((catalogue) => {
    const entries = statements
      .filter((item) => item.catalogues.includes(catalogue))
      .map((item) => `\t${JSON.stringify(item.name)}: ${goString(item.contract)},`)
      .join("\n");
    return `var ${catalogue}StatementRegistry = map[string]string{\n${entries}\n}`;
  });
  const source = `// Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.\n\npackage workhorse\n\n${groups.join("\n\n")}\n`;
  return execFileSync("gofmt", { input: source, encoding: "utf8" });
}

function renderTypeScript(statements: Statement[]): string {
  const entries = statements
    .map((item) => `  ${JSON.stringify(item.name)}: ${JSON.stringify(item.contract)},`)
    .join("\n");
  const source = `// Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.\nexport const SQL_STATEMENTS = {\n${entries}\n} as const;\n`;
  return execFileSync("pnpm", ["exec", "oxfmt", "--stdin-filepath=sql-catalogue.generated.ts"], {
    cwd: repository,
    input: source,
    encoding: "utf8",
  });
}

function renderPython(statements: Statement[]): string {
  const entries = statements
    .map((item) => {
      const psycopg = item.contract.replace(/\$\d+/g, "%s");
      return `    ${pythonString(item.name)}: (${pythonString(psycopg)}, ${pythonString(item.contract)}),`;
    })
    .join("\n");
  const fields = Object.keys(pythonBindings)
    .map((name) => `    ${name}: DriverStatement`)
    .join("\n");
  const values = Object.entries(pythonBindings)
    .map(([field, name]) => `    ${field}=_statement(${pythonString(name)}),`)
    .join("\n");
  const source = `# Code generated by scripts/generate-sql-catalogues.ts; DO NOT EDIT.\n# ruff: noqa: E501\n\nfrom __future__ import annotations\n\nfrom dataclasses import dataclass\nfrom typing import Literal\n\nDriverDialect = Literal["psycopg", "asyncpg"]\n\n\n@dataclass(frozen=True)\nclass DriverStatement:\n    psycopg: str\n    asyncpg: str\n\n    def for_dialect(self, dialect: DriverDialect) -> str:\n        return self.psycopg if dialect == "psycopg" else self.asyncpg\n\n\nSQL_STATEMENTS: dict[str, tuple[str, str]] = {\n${entries}\n}\n\n\ndef _statement(name: str) -> DriverStatement:\n    psycopg, asyncpg = SQL_STATEMENTS[name]\n    return DriverStatement(psycopg=psycopg, asyncpg=asyncpg)\n\n\n@dataclass(frozen=True)\nclass StatementRegistry:\n${fields}\n\n\nSTATEMENTS = StatementRegistry(\n${values}\n)\n`;
  return execFileSync("uv", ["run", "--project", "python", "ruff", "format", "-"], {
    cwd: repository,
    input: source,
    encoding: "utf8",
  });
}

async function readPythonSources(): Promise<PythonSource[]> {
  const sourceRoot = path.join(repository, "python/src/workhorse");
  const sources: PythonSource[] = [];

  async function inspect(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        await inspect(filename);
        continue;
      }
      if (!entry.name.endsWith(".py") || filename === path.join(sourceRoot, "_statements.py")) {
        continue;
      }
      sources.push({
        filename: path.relative(repository, filename),
        source: await readFile(filename, "utf8"),
      });
    }
  }

  await inspect(sourceRoot);
  return sources;
}

async function emit(relative: string, contents: string): Promise<void> {
  const filename = path.join(repository, relative);
  if (check) {
    const current = await readFile(filename, "utf8").catch(() => "");
    if (current !== contents)
      throw new Error(`${relative} is stale; run pnpm sql-catalogues:generate`);
    return;
  }
  await writeFile(filename, contents);
}

async function assertNoInlineTypeScriptSql(): Promise<void> {
  const sourceRoot = path.join(repository, "typescript/core/src");
  const allowedDynamicSql = new Set(["cli/reset-db.ts", "notifications.ts"]);
  const violations: string[] = [];

  async function inspect(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        await inspect(filename);
        continue;
      }
      if (!entry.name.endsWith(".ts") || entry.name.endsWith(".generated.ts")) continue;
      const relative = path.relative(sourceRoot, filename);
      if (allowedDynamicSql.has(relative)) continue;
      const source = await readFile(filename, "utf8");
      const sourceFile = ts.createSourceFile(filename, source, ts.ScriptTarget.Latest, true);
      function visit(node: ts.Node): void {
        if (
          ts.isCallExpression(node) &&
          ts.isPropertyAccessExpression(node.expression) &&
          node.expression.name.text === "query" &&
          node.arguments[0] !== undefined &&
          (ts.isStringLiteral(node.arguments[0]) ||
            ts.isTemplateExpression(node.arguments[0]) ||
            ts.isNoSubstitutionTemplateLiteral(node.arguments[0]))
        ) {
          const line =
            sourceFile.getLineAndCharacterOfPosition(node.arguments[0].getStart()).line + 1;
          violations.push(`${path.relative(repository, filename)}:${line}`);
        }
        ts.forEachChild(node, visit);
      }
      visit(sourceFile);
    }
  }

  await inspect(sourceRoot);
  if (violations.length > 0) {
    throw new Error(`TypeScript SQL must come from SQL_STATEMENTS:\n${violations.join("\n")}`);
  }
}

const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as Manifest;
if (!manifest.statements?.length) throw new Error("manifest statements catalogue is empty");
const names = new Set<string>();
for (const statement of manifest.statements) {
  if (names.has(statement.name)) throw new Error(`duplicate statement ${statement.name}`);
  names.add(statement.name);
  if (arity(statement.contract) !== statement.arity)
    throw new Error(`${statement.name} has the wrong arity`);
}
const pythonSources = await readPythonSources();
const pythonAccesses = findPythonStatementAccesses(pythonSources, path.join(repository, "python"));
assertPythonStatementBindings(pythonBindings, names, pythonAccesses);
if (check) await assertNoInlineTypeScriptSql();
await Promise.all([
  emit("go/sql_catalogue_generated.go", renderGo(manifest.statements)),
  emit(
    "typescript/core/src/queue/sql-catalogue.generated.ts",
    renderTypeScript(manifest.statements),
  ),
  emit("python/src/workhorse/_statements.py", renderPython(manifest.statements)),
]);
