import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { assertSchemaSourceOrder } from "./schema-source-order.js";

const repository = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(repository, "sql", "schema", "current.sql");
const artifactPath = path.join(repository, "sql", "schema.sql");
const generatedNotice =
  "-- Generated from sql/schema/current.sql. Do not edit this file directly.\n\n";

const source = await readFile(sourcePath, "utf8");
assertSchemaSourceOrder(source);
await writeFile(artifactPath, `${generatedNotice}${source}`);
