import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { writeOrCheck } from "./api-snapshot.js";
import { repositoryRoot } from "./packages.js";

/**
 * Write or verify `api/go.txt`, the accepted breaks in the Go module's exported surface.
 *
 * ADR 0054 delegates the Go surface to Go's own standard: a break is what `apidiff` calls an
 * incompatible change. `apidiff` compares two module versions, so the check needs a version to
 * compare against, and while the line is `0.x` a minor is allowed to break. Those two facts make
 * the committed artifact a list rather than a snapshot: it pins the published tag the comparison
 * starts from, and it names every incompatible change accepted since. A change absent from the
 * list fails the check by name.
 *
 * Only incompatible changes are listed, so an addition never asks for a regeneration.
 *
 * The pinned tag is data rather than a lookup because CI checks out without tags. `generate` reads
 * the newest `go/v*` tag this checkout has and re-pins to it, which is the release-time step that
 * empties the list; `check` reads the pinned line and never consults Git.
 */

// Pinned the way `go:lint` pins staticcheck, so a comparison does not change under the check.
//
// `go run` builds the tool with the toolchain already installed, because `actions/setup-go` sets
// GOTOOLCHAIN=local. So the pin has to name an `x/exp` commit whose own `go` directive is no newer
// than `go/go.mod`. Newer commits ask for go 1.26, and under GOTOOLCHAIN=local the check fails
// before it compares anything. Re-pin only alongside a `go/go.mod` bump.
const apidiffVersion = "v0.0.0-20260820122028-d6e0b57b1a69";
const goModule = "github.com/stablemates/workhorse/go";
const snapshotPath = "api/go.txt";
const check = process.argv.includes("--check");

const header = [
  "# Accepted breaks in the public Go API",
  "#",
  "# Generated by `pnpm go-api:generate`. ADR 0054 governs this surface: a break is what apidiff",
  "# calls an incompatible change to an exported identifier of a non-internal package. Every line",
  "# below is a break already accepted against the pinned tag, which a 0.x minor is allowed to",
  "# make. A break that is not listed fails `pnpm go-api:check`. Publishing a tag and running the",
  "# generator re-pins the baseline and empties the list. An addition is compatible and is never",
  "# listed, so adding never asks for a regeneration.",
  "",
].join("\n");

interface Baseline {
  /** Module version the comparison starts from, for example `v0.1.0-beta.1`. */
  readonly version: string;
  /** Git tag that published it, for example `go/v0.1.0-beta.1`. */
  readonly tag: string;
}

async function run(command: string, args: readonly string[], cwd: string): Promise<string> {
  return await new Promise<string>((resolve, reject) => {
    const child = spawn(command, [...args], { cwd, stdio: ["ignore", "pipe", "inherit"] });
    let output = "";
    child.stdout.setEncoding("utf8");
    child.stdout.on("data", (chunk: string) => {
      output += chunk;
    });
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (code === 0) resolve(output);
      else reject(new Error(`${command} ${args.join(" ")} exited with ${signal ?? String(code)}`));
    });
  });
}

/** The pinned baseline, read from the committed list. */
async function pinnedBaseline(): Promise<Baseline> {
  const current = await readFile(path.join(repositoryRoot, snapshotPath), "utf8").catch(() => "");
  const line = /^baseline (?<module>\S+)@(?<version>\S+) \(tag (?<tag>\S+)\)$/m.exec(current);
  if (!line?.groups) {
    throw new Error(
      `${snapshotPath} pins no baseline; run pnpm go-api:generate from a checkout with the go/v* tags`,
    );
  }
  if (line.groups.module !== goModule) {
    throw new Error(`${snapshotPath} pins ${line.groups.module}, not ${goModule}`);
  }
  return { version: line.groups.version!, tag: line.groups.tag! };
}

/**
 * The newest published `go/v*` tag in this checkout.
 *
 * Refusing rather than comparing against nothing: a check with no baseline would pass every
 * removal silently, which is the failure this whole gate exists to prevent.
 */
async function newestBaseline(): Promise<Baseline> {
  const tag = (await run("git", ["tag", "--list", "go/v*", "--sort=-v:refname"], repositoryRoot))
    .split("\n")
    .find((candidate) => candidate !== "");
  if (tag === undefined) {
    throw new Error(
      `No go/v* tag in this checkout, so there is nothing to compare the Go API against.` +
        ` Fetch tags with git fetch --tags, or publish the first one.`,
    );
  }
  return { version: tag.slice("go/".length), tag };
}

/**
 * Incompatible changes between the baseline version and this working tree.
 *
 * `apidiff` reads the baseline from the module cache, so the version is downloaded into a scratch
 * module first. Its own note asks to be run from the directory holding the module definition, and
 * the cache entry is exactly that directory.
 */
async function incompatibleChanges(baseline: Baseline): Promise<string[]> {
  const scratch = await mkdtemp(path.join(tmpdir(), "workhorse-go-api-"));
  try {
    await writeFile(path.join(scratch, "go.mod"), "module workhorse-go-api-baseline\n\ngo 1.25\n");
    await run("go", ["mod", "download", `${goModule}@${baseline.version}`], scratch);
    const cache = (await run("go", ["env", "GOMODCACHE"], scratch)).trim();
    const published = path.join(cache, ...`${goModule}@${baseline.version}`.split("/"));
    const exportData = path.join(scratch, "baseline.api");
    await run(
      "go",
      ["run", `golang.org/x/exp/cmd/apidiff@${apidiffVersion}`, "-m", "-w", exportData, goModule],
      published,
    );
    const changes = await run(
      "go",
      [
        "run",
        `golang.org/x/exp/cmd/apidiff@${apidiffVersion}`,
        "-m",
        "-incompatible",
        exportData,
        goModule,
      ],
      path.join(repositoryRoot, "go"),
    );
    // apidiff walks the module's packages in map order, so the same tree can report the same
    // changes in a different sequence. Sorting makes the committed list canonical.
    return changes
      .split("\n")
      .filter((line) => line !== "")
      .toSorted((left, right) => (left === right ? 0 : left < right ? -1 : 1));
  } finally {
    await rm(scratch, { recursive: true, force: true });
  }
}

const baseline = check ? await pinnedBaseline() : await newestBaseline();
const changes = await incompatibleChanges(baseline);
const body = changes.length === 0 ? "" : `${changes.join("\n")}\n`;

await writeOrCheck(
  {
    path: snapshotPath,
    generateCommand: "pnpm go-api:generate",
    meaning:
      "An unaccepted break is one apidiff reports and this file does not list, and ADR 0054 makes it breaking.",
    goneLabel: "no longer reported",
    arrivedLabel: "not yet accepted",
  },
  `${header}\nbaseline ${goModule}@${baseline.version} (tag ${baseline.tag})\n\n${body}`,
  check,
);
