import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repository = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(repository, "sql", "schema", "current.sql");
const artifactPath = path.join(repository, "sql", "schema.sql");
const generatedNotice =
  "-- Generated from sql/schema/current.sql. Do not edit this file directly.\n\n";

const source = await readFile(sourcePath, "utf8");
const artifact = `${generatedNotice}${source}`;

if (process.argv.includes("--check")) {
  const current = await readFile(artifactPath, "utf8").catch(() => "");
  if (current !== artifact) {
    throw new Error("sql/schema.sql is stale; run pnpm schema:generate");
  }
} else {
  await writeFile(artifactPath, artifact);
}
