/**
 * Run a repository command against the databases belonging to *this* checkout.
 *
 * `node --env-file` deliberately loses to variables already present in the environment, which is
 * the wrong precedence for a repository whose worktrees each own a set of databases. A shell that
 * exported one checkout's repository database URLs carries them into a command run from
 * another checkout, and that command then quietly reads and resets the first checkout's data.
 *
 * Interactive shells hide this when a directory-aware loader such as mise or direnv re-exports on
 * every `cd`. Anything that changes directory without that hook — an agent, a script, a CI step —
 * does not, so correctness cannot rest on the loader being active.
 *
 * The variables generated by the checkout setup scripts therefore take their value from this
 * checkout's `.env` unconditionally. When there is no checkout file, CI-provided database URLs
 * retain their normal environment precedence. Every other variable keeps the familiar
 * `--env-file` precedence, so a deliberate one-off override such as `PORT=4000 pnpm demo` still
 * works.
 *
 * A linked worktree whose `.env` still names the primary checkout's databases — the shape a
 * worktree has when a tool copied `.env` in without running `pnpm worktree:setup` — is refused
 * outright. Two such worktrees running database-scope tests at once reset each other mid-suite.
 *
 * The wrapper also refuses a command whose tool does not identify itself, because a substituted
 * tool reports a pass without doing the work. See `verify-toolchain.ts`.
 *
 * Usage: tsx scripts/with-env.ts <command> [...arguments]
 */
import { spawn } from "node:child_process";
import { join, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";
import {
  localDatabaseEnvironmentVariable,
  localDatabasePurposes,
} from "../typescript/core/src/local-database.js";
import { readEnvironment } from "./environment-file.js";
import { gofmtTool, readPins, toolsNamedBy, verifyTools } from "./verify-toolchain.js";
import {
  describeUnscopedDatabases,
  linkedWorktreeId,
  unscopedDatabases,
} from "./worktree-identity.js";

/** Variables this repository provisions per worktree, and so is entitled to overwrite. */
const ownedVariables = new Set(
  localDatabasePurposes.map((purpose) => localDatabaseEnvironmentVariable(purpose)),
);

const [command, ...commandArguments] = process.argv.slice(2);
if (!command) {
  console.error("Usage: tsx scripts/with-env.ts <command> [...arguments]");
  process.exit(2);
}

// Resolved against this file rather than the working directory: the point is to find the `.env`
// of the checkout the command belongs to, whatever directory it was invoked from.
const checkoutRoot = resolvePath(fileURLToPath(new URL("..", import.meta.url)));
const fileEnvironment = await readEnvironment(join(checkoutRoot, ".env"));

const worktreeId = await linkedWorktreeId(checkoutRoot);
if (worktreeId !== undefined) {
  const unscoped = unscopedDatabases(fileEnvironment, worktreeId);
  if (unscoped.length > 0) {
    console.error(describeUnscopedDatabases(worktreeId, checkoutRoot, unscoped));
    process.exit(2);
  }
}

// A substituted tool turns a check into a false pass, so the tool this wrapper is about to start
// has to identify itself before it starts. Only identity is asserted here, not agreement with the
// `mise.toml` pin: CI runs the support matrix through this wrapper, and those Node, Python and Go
// versions differ from the pins deliberately. `pnpm check` and the `pre-push` hook assert the pins.
const pins = await readPins(checkoutRoot);
const toolRefusals = await verifyTools(
  toolsNamedBy(command, commandArguments, new Set([...pins.keys(), gofmtTool])),
  { mode: "identity", pins, checkoutRoot },
);
if (toolRefusals.length > 0) {
  console.error(toolRefusals.join("\n\n"));
  process.exit(2);
}

const environment: NodeJS.ProcessEnv = { ...process.env };
for (const [key, value] of Object.entries(fileEnvironment)) {
  if (ownedVariables.has(key) || environment[key] === undefined) environment[key] = value;
}

const child = spawn(command, commandArguments, {
  cwd: checkoutRoot,
  env: environment,
  stdio: "inherit",
});

for (const signal of ["SIGINT", "SIGTERM"] as const) {
  process.on(signal, () => child.kill(signal));
}

const exitCode = await new Promise<number | null>((resolve, reject) => {
  child.once("error", reject);
  child.once("exit", resolve);
});
process.exitCode = exitCode ?? 1;
